<?php include 'drupal-css.inc'; ?>



<?php  $timestamp = time() ?>
<link href="../dist/vendor/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet" type="text/css">
<link href="../dist/vendor/lightSlider/lightslider.min.css"
      rel="stylesheet" type="text/css">

<link href="../dist/vendor/slick/slick.css" rel="stylesheet" type="text/css">
<link href="../dist/css/styles.css?t=<?php  print $timestamp?>" rel="stylesheet" type="text/css">
