<script type="text/javascript" src="common/js/lib/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="../dist/vendor/jquery.cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="../dist/vendor/device/device.js"></script>
<script type="text/javascript" src="../dist/vendor/select2/select2.full.min.js"></script>
<script type="text/javascript" src="../dist/vendor/slick/slick.min.js"></script>
<script type="text/javascript" src="../dist/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
<script type="text/javascript" src="../dist/vendor/flexslider/jquery.flexslider.min.js"></script>
<script type="text/javascript"
  src="../dist/vendor/lightSlider/lightslider.min.js"></script>

<script type="text/javascript" src="../dist/js/index.js?t=<?php  print $timestamp?>"></script>
<!--<script type="text/javascript" src="../dist/js/index.min.js?t=--><?php // print $timestamp?><!--"></script>-->
