<?php
/**
 * @file
 * Custom module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function custom_module_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (preg_match('/webform_submission_subcommittee_notifications/', $form_id)) {
    $view_id = Drupal::routeMatch()->getParameter('view_id');

    if (!empty($view_id)) {
      switch ($view_id) {
        case 'subcommittee_events':
          $current_path = \Drupal::service('path.current')->getPath();
          $arg  = explode('/', $current_path);
          if (!empty($arg[2]) && is_numeric($arg[2])) {
            $form['actions']['submit']['#validate'][] = 'custom_module_add_committee';
          }
          break;
      }
    }
  }
}

function custom_module_add_committee($form, FormStateInterface $form_state) {
  $view_id = Drupal::routeMatch()->getParameter('view_id');

  if (!empty($view_id)) {
    switch ($view_id) {
      case 'subcommittee_events':
        $current_path = \Drupal::service('path.current')->getPath();
        $arg  = explode('/', $current_path);
        if (!empty($arg[2]) && is_numeric($arg[2])) {
          $form_state->setValue('committee', $arg[2]);
        }
        break;
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function custom_module_views_query_alter(\Drupal\views\ViewExecutable $view,
                                                   \Drupal\views\Plugin\views\query\Sql $query) {

  if ($view->id() == 'week_review' && $view->getDisplay()->display['id'] == 'page_1') {
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT(node__field_week_review_date.field_week_review_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'press_releases' && $view->getDisplay()->display['id'] == 'page_1') {
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT((node__field_date.field_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'journals' && $view->getDisplay()->display['id'] == 'page_1') {
    $table_files = $query->getTableInfo('node__field_journals_files');
    $table_files['join']->field = 'field_journals_files_target_id';
    $table_files["join"]->configuration["field"] = 'field_journals_files_target_id';

    $table_node = $query->getTableInfo('field_journals_files_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';

    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT(paragraph__field_journals_files_date.field_journals_files_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'calendar_lt_st_journals' && $view->getDisplay()->display['id'] == 'block_1') {
    $table_files = $query->getTableInfo('node__field_journals_files');
    $table_files['join']->field = 'field_journals_files_target_id';
    $table_files["join"]->configuration["field"] = 'field_journals_files_target_id';

    $table_node = $query->getTableInfo('field_journals_files_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'calendar_lt_joint_app_bd' && $view->getDisplay()->display['id'] == 'block_1') {
    $table_files = $query->getTableInfo('node__field_cl_app_bud_calendar');
    $table_files['join']->field = 'field_cl_app_bud_calendar_target_id';
    $table_files["join"]->configuration["field"] = 'field_cl_app_bud_calendar_target_id';

    $table_node = $query->getTableInfo('field_cl_app_bud_calendar_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
}
