<?php
/**
 * @file
 * Custom module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Database\Query\Condition;

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function custom_module_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if (preg_match('/webform_submission_subcommittee_notifications/', $form_id)) {
    $view_id = Drupal::routeMatch()->getParameter('view_id');

    if (!empty($view_id)) {
      switch ($view_id) {
        case 'subcommittee_events':
          $current_path = \Drupal::service('path.current')->getPath();
          $arg  = explode('/', $current_path);
          if (!empty($arg[2]) && is_numeric($arg[2])) {
            $form['actions']['submit']['#validate'][] = 'custom_module_add_committee';
          }
          break;
      }
    }
  }
  switch ($form_id){
    case 'webform_submission_contact_senator_node_3945_add_form':
      $senator_nid = \Drupal::request()->query->get('sid');
      $form['elements']['mail_to']['#access'] = FALSE;

      if (!empty($senator_nid) && is_numeric($senator_nid)) {
        $node = \Drupal\node\Entity\Node::load($senator_nid);
        if (!empty($node) && ($node->getType() == 'senator')){
          $form['elements']['select_your_senator']['#default_value'] = $senator_nid;
          $form['elements']['select_your_senator']['#access'] = FALSE;
        }
      }

      $form['actions']['submit']['#validate'][] = 'custom_module_contact_senator_validate';
      break;
    case 'node_senate_votes_edit_form':
      $current_path = \Drupal::service('path.current')->getPath();
      $path_args = explode('/', $current_path);
      $arg_0 = !empty($path_args[1]) ? $path_args[1] : '';
      $arg_1 = !empty($path_args[2]) ? $path_args[2] : '';
      $nid = ($arg_0 == 'node') && is_numeric($arg_1) ? $arg_1 : '';

      if (!empty($nid) && !empty($form["field_senate_votes"])) {
        $options['target'] = '_blank';
        $url = Url::fromUserInput('/manage/senate-votes/' . $nid);
        $url->setOption('attributes', $options);
        $manage_link = Link::fromTextAndUrl(t('Manage Senate Votes'), $url);
        $form["field_senate_votes"] = [
          '#theme' => 'markup',
          '#markup' => $manage_link->toString(),
        ];
      }
      break;
  }

}

function custom_module_add_committee($form, FormStateInterface $form_state) {
  $view_id = Drupal::routeMatch()->getParameter('view_id');

  if (!empty($view_id)) {
    switch ($view_id) {
      case 'subcommittee_events':
        $current_path = \Drupal::service('path.current')->getPath();
        $arg  = explode('/', $current_path);
        if (!empty($arg[2]) && is_numeric($arg[2])) {
          $form_state->setValue('committee', $arg[2]);
          $mailchimp_group = _custom_module_mailchimp_commitee_map($arg[2]);

          if (!empty($mailchimp_group)) {
            $form_state->setValue('mailchimp_committee', $mailchimp_group);
          }
        }
        break;
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function custom_module_views_query_alter(\Drupal\views\ViewExecutable $view,
                                                   \Drupal\views\Plugin\views\query\Sql $query) {

  if ($view->id() == 'week_review' && $view->getDisplay()->display['id'] == 'page_1') {
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT(node__field_week_review_date.field_week_review_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if (in_array($view->id(), ['press_releases', 'press_releases_audio', 'senator_press_release']) && $view->getDisplay()->display['id'] == 'page_1') {
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT((node__field_date.field_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'journals' && $view->getDisplay()->display['id'] == 'page_1') {
    $table_files = $query->getTableInfo('node__field_journals_files');
    $table_files['join']->field = 'field_journals_files_target_id';
    $table_files["join"]->configuration["field"] = 'field_journals_files_target_id';

    $table_node = $query->getTableInfo('field_journals_files_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';

    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT(paragraph__field_journals_files_date.field_journals_files_date_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'calendar_lt_st_journals' && $view->getDisplay()->display['id'] == 'block_1') {
    $table_files = $query->getTableInfo('node__field_journals_files');
    $table_files['join']->field = 'field_journals_files_target_id';
    $table_files["join"]->configuration["field"] = 'field_journals_files_target_id';

    $table_node = $query->getTableInfo('field_journals_files_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'calendar_lt_joint_app_bd' && $view->getDisplay()->display['id'] == 'block_1') {
    $table_files = $query->getTableInfo('node__field_cl_app_bud_calendar');
    $table_files['join']->field = 'field_cl_app_bud_calendar_target_id';
    $table_files["join"]->configuration["field"] = 'field_cl_app_bud_calendar_target_id';

    $table_node = $query->getTableInfo('field_cl_app_bud_calendar_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'search_statutes_constitutions' && $view->getDisplay()->display['id'] == 'page_1') {
    $configuration = [
      'type'       => 'LEFT',
      'table'      => 'search_index',
      'field'      => 'sid',
      'left_table' => 'file_managed',
      'left_field' => 'fid',
      'operator'   => '=',
      'extra' => [
        0 => [
          'field' => 'type',
          'value' => 'file_search',
        ],
      ],
    ];

    $join = \Drupal\views\Views::pluginManager('join')
      ->createInstance('standard', $configuration);
    $rel = $query->addRelationship('search', $join, 'file_managed');
    $query->addTable('search_index', $rel, $join, 'search_index');

    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        $field_str = is_object($condition['field']) ? $condition['field']->conditions() : '';
        if (!empty($field_str) && strpos($field_str[0]['field'], 'file_managed') !== FALSE) {
          $condition['field']->condition('search.word', $field_str[0]["value"], $field_str[0]["operator"]);
        }
      }
    }

    $exposed_input = $view->getExposedInput();
    if (!empty($exposed_input)) {
      $type = !empty($exposed_input["constitutions"]) && !empty($exposed_input["op"]) &&
        ($exposed_input["op"] == 'constitutions_submit') ? 'constitutions' : '';
      $type = empty($type) && !empty($exposed_input["statutes"]) ? 'statutes' : $type;

      if (!empty($type)) {
        $configuration = [
          'type'       => 'LEFT',
          'table'      => 'node__field_statutes_constit_type',
          'field'      => 'entity_id',
          'left_table' => 'field_statutes_constit_files_file_managed',
          'left_field' => 'nid',
          'operator'   => '=',
          'extra' => [
            0 => [
              'field' => 'bundle',
              'value' => 'statutes_constit',
            ],
          ],
        ];

        $join = \Drupal\views\Views::pluginManager('join')
          ->createInstance('standard', $configuration);
        $rel = $query->addRelationship('constit_type', $join, 'field_statutes_constit_files_file_managed');
        $query->addTable('node__field_statutes_constit_type', $rel, $join, 'constit');

        $query->addWhere('', 'constit_type.field_statutes_constit_type_value', $type, '=');

        //      $a = $query->query()->__toString();
      }
    }
  }
  if ($view->id() == 'home_committee_events') {
    $end_date = FALSE;
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT((node__field_comt_evt_date.field_comt_evt_date_value') !== FALSE) {
          $sign = $end_date ? '<=' : '>=';
          $condition['field'] = str_replace('=', $sign, $condition['field']);
          $end_date = TRUE;
        }
      }
    }
  }
  if ($view->id() == 'senate_staff' && $view->getDisplay()->display['id'] == 'page_1') {
    $table_files = $query->getTableInfo('node__field_staff');
    $table_files['join']->field = 'field_staff_target_id';
    $table_files["join"]->configuration["field"] = 'field_staff_target_id';

    $table_node = $query->getTableInfo('field_staff_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'manage_senate_votes' && $view->getDisplay()->display['id'] == 'page_1') {
    $table_files = $query->getTableInfo('node__field_senate_votes');
    $table_files['join']->field = 'field_senate_votes_target_id';
    $table_files["join"]->configuration["field"] = 'field_senate_votes_target_id';

    $table_node = $query->getTableInfo('field_senate_votes_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'senate_artwork' && $view->getDisplay()->display['id'] == 'page_1') {
    $exposed_input = $view->getExposedInput();
    $location = !empty($exposed_input["location"]) ? $exposed_input["location"] : '';
    $location = strtolower($location);
    $has_outer = (strpos($location, 'out') !== FALSE);
    $has_senate = (strpos($location, 'senate') !== FALSE);
    $table_caption = $query->getTableInfo('node__field_edu_indiv_art_work_cap');

    if (!$has_outer && !empty($table_caption)) {
      $query->addWhere('', 'node__field_edu_indiv_art_work_cap.field_edu_indiv_art_work_cap_value', '%out%', 'NOT LIKE');
    }
    if ($has_senate) {
      $location_exp = explode(' ', $location);
      $word_count = count($location_exp);
      if (($word_count < 3) && !empty($table_caption)) {
        $query->addWhere('', 'node__field_edu_indiv_art_work_cap.field_edu_indiv_art_work_cap_value', '%' . $location . '%', 'LIKE');
      }
    }
  }
  if ($view->id() == 'senators' && $view->getDisplay()->display['id'] == 'page_1') {
    $formula = 'SUBSTR(node_field_data.title, INSTR(node_field_data.title, \' \'))';
    $query->addField(NULL, $formula, 'second_name');
    $query->addOrderBy(NULL, NULL, 'ASC', 'second_name');
  }
  if ($view->id() == 'senator_rec_news_land' && $view->getDisplay()->display['id'] == 'page_1') {
    foreach ($query->where as $key => &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if (strpos($condition['field'], 'DATE_FORMAT((node__field_senator_blog_post_posted.field_senator_blog_post_posted_value') !== FALSE) {
          $condition['field'] = str_replace('%Y-%m-%d', '%Y-%m', $condition['field']);
        }
      }
    }
  }
  if ($view->id() == 'press_release_senators' && $view->getDisplay()->display['id'] == 'entity_reference_1') {
    $current_user = \Drupal::currentUser();
    $uid = $current_user->id();
    $roles = $current_user->getRoles();

    if (!in_array('administrator', $roles) && !in_array('manager', $roles)) {
      $query->addWhere('', 'node_field_data.uid', $uid, '=');
//      $a = $query->query()->__toString();
    }
  }
  if ($view->id() == 'senate_votes_inner' && $view->getDisplay()->display['id'] == 'block_1') {
    $table_vote = $query->getTableInfo('node__field_senate_votes');
    $table_vote['join']->field = 'field_senate_votes_target_id';
    $table_vote["join"]->configuration["field"] = 'field_senate_votes_target_id';

    $table_node = $query->getTableInfo('field_senate_votes_paragraphs_item_field_data');
    $table_node['join']->field = 'nid';
    $table_node["join"]->configuration["field"] = 'nid';
  }
  if ($view->id() == 'senators' && $view->getDisplay()->display['id'] == 'block_1') {
    $args = $view->args;
    if (!empty($args[0]) && is_numeric($args[0])) {
      $query->addWhere(2, (new Condition('OR'))
        ->condition('field_committee_chair_node_field_data.tid', '', 'IS NULL')
        ->condition('field_committee_chair_node_field_data.tid', $args[0], '!='));
      $query->addWhere(2, (new Condition('OR'))
        ->condition('field_committee_vice_chairman_node_field_data.tid', '', 'IS NULL')
        ->condition('field_committee_vice_chairman_node_field_data.tid', $args[0], '!='));
    }
  }
}

/**
 * Register form ajax callback -  for validate classes
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function custom_module_contact_form_ajax_callback($form, &$form_state) {
  $response = new AjaxResponse();
  $response->addCommand(new ReplaceCommand('#mail-to-ajax-wrapper',$form["elements"]["mail_to"]["mail_to_ajax_wrapper"]));

  return $response;
}

/**
 * Set senators mail.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function custom_module_contact_senator_validate($form, FormStateInterface &$form_state) {
  $user_input = $form_state->getValues();
  $senator_nid = !empty($user_input['select_your_senator']) && is_numeric($user_input['select_your_senator']) ?
    $user_input['select_your_senator'] : '';
  if (!empty($senator_nid)) {
    $email = _custom_module_get_senator_email($senator_nid);
    if (!empty($email)) {
      $form_state->setValue('mail_to', $email);
    }
    else {
      \Drupal::logger('error')
        ->error('See ' . __FUNCTION__ . '(). Empty senator email.');
    }
  }
}

function _custom_module_get_senator_email($nid) {
  if (empty($nid)) {
    return '';
  }

  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'senator')
    ->condition('nfd.status', 1)
    ->condition('nfd.nid', $nid);
  $query->innerJoin('users_field_data', 'ufd', 'ufd.uid = nfd.uid AND ufd.status = 1');
  $query->fields('ufd', ['mail']);

  $result = $query->execute()->fetchCol();
  return !empty($result) ? $result[0] : '';
}

function _custom_module_mailchimp_commitee_map($tid) {
  $map = [
    '68' => '34cacb43b4',
    '67' => '5fcc45545c',
    '85' => '3f95e020d6',
    '86' => 'b672de2712',
    '87' => '76091e1f58',
    '84' => '36f616dad0',
    '83' => 'dcf7a9a164',
    '82' => '20012d927a',
    '69' => '03df5d06c3',
    '70' => '2b1109ecd9',
    '71' => '88edf99954',
    '72' => 'f7ac316d53',
    '73' => '4e3ee65d72',
    '74' => '49b253570a',
    '75' => 'd30c6731fa',
    '76' => '1bfbd589f7',
    '77' => '884f58114c',
    '78' => '9a23cdd8d1',
    '79' => 'c97d4a4d2f',
    '80' => '9d92c93616',
  ];
  return !empty($map[$tid]) ? $map[$tid] : '';
}

/**
 * Implements hook_views_data_alter().
 */
function custom_module_views_data_alter(array &$data) {
  if (isset($data['node__field_senator'])) {
    // Create a new views argument
    $data['node__field_senator']['custom_nid_author'] = [
      'title' => t('Custom: Senator nid to Senator node author'),
      'group' => t('Custom'),
      'title short' => t('Nid to Author'),
      'argument' => [
        'table' => 'node__field_senator',
        'field' => 'field_senator_target_id',
        'id' => 'custom_senator_nid_author',
        'zero is null' => TRUE,
      ],
    ];
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function custom_module_page_attachments_alter(array &$page) {
  global $base_url;
  $html_head = !empty($page['#attached']['html_head']) ? $page['#attached']['html_head'] : [];
  $theme_path = $base_url . '/' . drupal_get_path('theme', 'senate');
  $has_og_image = FALSE;
  $has_tw_image = FALSE;

  foreach ($html_head as $key => $head) {
    $tag = !empty($head[1]) ? $head[1] : '';
    $tag_number = str_replace('og_image_', '', $tag);
    $tag_number = str_replace('twitter_cards_image_', '', $tag_number);

    if (($tag == 'og_image') || ((strpos($tag, 'og_image') !== FALSE) && is_numeric($tag_number))) {
      $attributes = !empty($head[0]["#attributes"]) ? $head[0]["#attributes"] : [];
      $attr_name = !empty($attributes["property"]) ? $attributes["property"] : '';

      if ($attr_name == 'og:image') {
        $has_og_image = TRUE;
      }
    }
    elseif (($tag == 'twitter_cards_image') || ((strpos($tag, 'twitter_cards_image') !== FALSE) && is_numeric($tag_number))) {
      $attributes = !empty($head[0]["#attributes"]) ? $head[0]["#attributes"] : [];
      $attr_name = !empty($attributes["name"]) ? $attributes["name"] : '';

      if ($attr_name == 'twitter:image') {
        $has_tw_image = TRUE;
      }
    }

    if ($head[1] == 'system_meta_generator') {
      unset($page['#attached']['html_head'][$key]);
    }
  }

  if (!$has_og_image) {
    $og_image = [
      '#tag' => 'meta',
      '#attributes' => [
        'property' => 'og:image',
        'content' => $theme_path . '/dist/images/senate-share-photo-generic.jpg',
      ],
    ];
    $page['#attached']['html_head'][] = [$og_image, 'custom_module_og'];
  }

  if (!$has_tw_image) {
    $tw_image = [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'twitter:image',
        'content' => $theme_path . '/dist/images/senate-share-photo-generic.jpg',
      ],
    ];
    $page['#attached']['html_head'][] = [$tw_image, 'custom_module_tw'];
  }
}
