<div class="bEvents__item">
  <a href="../dist/images/events/<?php print $element[0]; ?>" class="bEvents__imgWrap">
     <span class="bEvents__img"
           style="background-image: url('../dist/images/events/<?php print $element[0]; ?>')">
     </span>
  </a>
  <div class="bEvents__body">
    <div class="bEvents__desc">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad asperiores blanditiis corporis quibusdam. Aliquid architecto at autem, dicta ea eligendi expedita, molestiae non omnis pariatur quia reiciendis reprehenderit rerum sunt.
    </div>
  </div>

</div>