<div class="bEvents__item" data-videoId="XVsjLNUK-pw">
  <a href="#" class="bEvents__imgWrap">
     <span class="bEvents__img"
           style="background-image: url('../dist/images/events/<?php print $element[0]; ?>')">
     </span>
    <span class="bEvents__play"></span>
  </a>
  <span class="bEvents__body">
    <a href="#" class="bEvents__title">
     <?php print $element[1]; ?>
    </a>
    <span class="bEvents__date">
      <?php print $element[2]; ?>
    </span>
    <span class="bEvents__desc">
       <?php print $element[3]; ?>
    </span>
    <span class="bEvents__readMoreWr">
       <a href="#" class="btn btn_a bEvents__readMore">watch video</a>
    </span>
  </span>
</div>