<?php

/**
 * @file
 * Contains events_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\File\FileSystem;
use Drupal\senate_votes\Clients\FetchClient;
use Drupal\senate_votes\Clients\XmlFileClient;
use Drupal\senate_votes\Clients\XmlFileDbClient;
use Drupal\senate_votes\Clients\XmlFileJobDevider;

/**
 * Implements hook_cron().
 */
function senate_votes_cron() {
  $cron_config = \Drupal::configFactory()->getEditable('senate_votes.settings');
  $interval = $cron_config->get('interval');
  $request_time = \Drupal::time()->getRequestTime();
  $state = _senate_votes_get_state_values();

  if ($request_time >= $state['next_execution']) {
    \Drupal::logger('senate_votes')->notice('senate_votes ran');

    if ($state['show_status_message']) {
      \Drupal::messenger()
        ->addMessage(t('senate_votes executed at %time', ['%time' => date('c')]));
      \Drupal::state()->set('senate_votes_show_status_message', FALSE);
    }

    _senate_votes_set_state_values($request_time, $interval);

    if ($state['source'] === 'files') {
      $xmlFileClient = new XmlFileClient($state['files_directory'], $state['prev_execution']);
      $xmlFileDbClient = new XmlFileDbClient($state['source']);
      $xmlFileJobDevider = new XmlFileJobDevider($xmlFileClient, $xmlFileDbClient, $state['files_update_all']);
      $items = $xmlFileJobDevider->getCronJobs();
      $queue = \Drupal::queue('senate_votes_api');
    }
    else {
      $client = new FetchClient($state['api_url']);
      $votes = $client->getVotes();
      $items = _senate_votes_divide_job_items($votes, $state['api_update_all'], $state['source']);
      $queue = \Drupal::queue('senate_votes_api');
    }

    foreach ($items as $item) {
      $item = (object) $item;
      $queue->createItem($item);
    }
  }
}

/**
 * Get state values.
 * @return array
 */
function _senate_votes_get_state_values() {
  return [
    'next_execution' => \Drupal::state()->get('senate_votes.next_execution', 0),
    'prev_execution' => \Drupal::state()->get('senate_votes.prev_execution', 0),
    'source' => \Drupal::state()->get('senate_votes.source', 'files'),
    'api_url' => \Drupal::state()->get('senate_votes.api_url', ''),
    'api_update_all' => \Drupal::state()->get('senate_votes.api_update_all', FALSE),
    'show_status_message' => \Drupal::state()->get('senate_votes_show_status_message', FALSE),
    'files_update_all' => \Drupal::state()->get('senate_votes.files_update_all', FALSE),
    'files_directory' => \Drupal::state()->get('senate_votes.directory', ''),
  ];
}

/**
 * Set state values.
 * @param $request_time
 * @param $interval
 *
 * @return void
 */
function _senate_votes_set_state_values($request_time, $interval) {
  $interval = !empty($interval) ? $interval : 3600;
  \Drupal::state()->set('senate_votes.next_execution', $request_time + $interval);
  \Drupal::state()->set('senate_votes.prev_execution', $request_time);
  \Drupal::state()->set('senate_votes.update_all', FALSE);
}

function _senate_votes_divide_job_items($votes, $update_all, $source) {
  $senate_votes_api_helper = \Drupal::hasService('senate_votes.api_helper') ?
    \Drupal::service('senate_votes.api_helper') : '';
  $senate_votes_helper = \Drupal::hasService('senate_votes.helper') ?
    \Drupal::service('senate_votes.helper') : '';
  $items = [];
  $votes_to_create = [];
  $limit = 50;
  $pids = [];

  if (!empty($senate_votes_api_helper) && !empty($votes)) {
    $db_votes_info = $senate_votes_api_helper->getDbVotesInfo($source);
    $db_votes = $db_votes_info['votes'];
    $pids = $db_votes_info['pids'];

    foreach ($votes as $vote) {
      $id = $senate_votes_api_helper->getVoteId($vote['date'], $vote['measure'], $vote['author'], $vote['action']);
      $year = $senate_votes_helper->getYear($vote['date']);

      if (!empty($db_votes[$year]) && (empty($db_votes[$year][$id]) || !empty($update_all))) {
        reset($db_votes[$year]);
        $first_row_data = current($db_votes[$year]);
        $nid = $first_row_data['nid'] ?? '';
        $votes_to_create[] = [
          'nid' => $nid,
          'vote' => $vote,
        ];
      }
      elseif (empty($db_votes[$year])) {
        $nid = _senate_votes_api_create_node($vote, $source);
        $votes_to_create[] = [
          'nid' => $nid,
          'vote' => $vote,
        ];
        $db_votes[$year] = [
          $id => ['nid' => $nid],
        ];
      }
    }
  }

  while (!empty($votes_to_create)) {
    $rows_part = array_splice($votes_to_create, 0, $limit);

    if (!empty($rows_part)) {
      $items[] = [
        'rows' => $rows_part,
        'pids' => $pids,
        'update_all' => $update_all,
      ];
    }
  }

  return $items;
}

function _senate_votes_api_create_node($data, $source, $file = '') {
  $senate_votes_helper = \Drupal::hasService('senate_votes.helper') ?
    \Drupal::service('senate_votes.helper') : '';

  $node_data['description'] = $data["description"] ?? '';
  $year = $data['date'] ?? '';
  $node_data['year'] = $senate_votes_helper->getYear($year);
  $node_data['title'] = $node_data['year'] . ' Votes';
  $node_data['type'] = $source;
  $node_data['file_name'] = $file;
  $parent_node = $senate_votes_helper->createNode($node_data);

  \Drupal::logger('senate_votes')
    ->notice(t('Node %nid has been created.', [
      '%nid' => $parent_node->id(),
    ]));

  return $parent_node->id();
}
