<?php

/**
 * @file
 * Functions to support theming in the senate theme.
 */

use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Render\Markup;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;
use Drupal\views\Views;
use Drupal\custom_module\Plugin\views\argument\CustomNidToAuthor;
use Drupal\taxonomy\Entity\Term;

define('SENATE_AGENCIES_DOC_BASE_PATH', '/committees/appropriations/education/agencies-documents');
define('SENATE_CONTACTS_LANDING_NID', '2469'); //first stage NID
define('SENATE_RESERVE_ROOM_NID', '5808'); //first stage NID
define('SENATE_SENATOR_RECENT_NEWS_URL', '/senator-news');

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function senate_preprocess_html(array &$vars) {

  if (!empty($vars) && ($vars['root_path'] == 'user' || $vars['root_path'] == 'editor')){
    $vars['attributes']['class'][] = 'page-authorization';
  }

  if (($node = \Drupal::request()->attributes->get('node')) && is_object($node)) {
      switch ($node->bundle()) {
        case 'user':
          break;
      }
    }
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function senate_preprocess_page(array &$vars) {
  $node = !empty($vars["node"]) ? $vars["node"] : '';
  $vars['path_to_theme'] = base_path() . drupal_get_path('theme', 'senate');

  $vars['subscribe_form_popup'] = [
    '#theme' => 'senate_subscribe_form',
    '#current_path' => $vars['path_to_theme']
  ];
  $view_id = \Drupal::routeMatch()->getParameter('view_id');

  $protocol = !empty($GLOBALS['is_https']) ?  'https://' : 'http://';
  $main_site_url = $protocol . ltrim(strstr($GLOBALS['base_url'], '.'), '.');

  $url = Url::fromUri($main_site_url);
  $options = ['class' => ['btn accessibility__btn-back contrast-only'], 'html' => TRUE];
  $url->setOption('attributes', $options);
  $vars['main_site_url'] = Link::fromTextAndUrl(t('back to <br> main site'), $url);

  if (!empty($view_id)) {
    switch ($view_id){
      case 'protem':
        $vars['video_popup'] = [
          '#theme' => 'senate_video_popup',
        ];
        break;
    }
  }
  if (!empty($node) && is_object($node)) {
    switch ($node->bundle()) {
      case 'protem_podcast':
        $vars['video_popup'] = [
          '#theme' => 'senate_video_popup',
        ];
        break;
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function senate_preprocess_node(array &$vars) {
  global $base_path;
  $node = $vars['node'];
  $view_mode = !empty($vars["view_mode"]) ? $vars["view_mode"] : '';
  $theme_path = $base_path . \Drupal::theme()
      ->getActiveTheme()
      ->getPath();

  $vars['socials'] = _senate_get_socials($node, 'node');

  if (!empty($node) && is_object($node)) {

    switch ($node->bundle()) {
      case 'homepage':
        $vars['search'] = _senate_get_block('searchapi_find_legislation');
        $vars['leadersip'] = _senate_get_block('leadership');

        $top_slider_enabled = (!empty($vars["content"]["field_home_top_slider_turn_on"]) &&
          !empty($vars["content"]["field_home_top_slider_turn_on"]['#items'])) ?
          $vars["content"]["field_home_top_slider_turn_on"]['#items']->getValue() : '';
        $vars['top_slider_enabled'] = (!empty($top_slider_enabled) && !empty($top_slider_enabled[0])) ?
          $top_slider_enabled[0]["value"] : '';

        $first_day_obj = new DrupalDateTime("this week");
        $last_day_obj = new DrupalDateTime("this week +6 days");
        $params = [$first_day_obj->format('Y-m-d'), $last_day_obj->format('Y-m-d')];
        $vars['week_events'] = _senate_get_view('home_committee_events', 'block_1', $params);
        break;
      case 'committee':
        $tree = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
          ->loadTree('committees', 0, NULL, FALSE);
        $tids = [];
        $first_level_tids = [];
        $params = [];
        foreach ($tree as $term) {
          $tids[] = $term->tid;
          $parent = (!empty($term->parents) && isset($term->parents[0])) ? $term->parents[0] : '';
          if ($parent === '0') {
            $first_level_tids[] = $term->tid;
          }
        }

        if (!empty($first_level_tids)) {
          $first_level_result = implode(',', $first_level_tids);
          $first_level_params = [$first_level_result];
          $vars['dropdown'] = _senate_get_view('committee_dropdown', 'block_1', $first_level_params);
        }
        if (!empty($tids)) {
          $result = implode(',', $tids);
          $month_obj = new DrupalDateTime("this month");

          $display_id = !empty($first_level_tids) ? 'block_2' : 'block_1';
          if ($display_id == 'block_1') {
            $params = [$result, $month_obj->format('Ym')];
          }
//          elseif ($display_id == 'block_2') {
//            $params = [$month_obj->format('Ym')];
//          }
          $vars['committee_events'] = _senate_get_view('committee_events', $display_id, $params);
        }

        $vars['sub_menu'] = _senate_get_block('senatestudiessubmenu');
        break;
      case 'committee_events':
        if ($view_mode == 'teaser') {
          $vars["attributes"]["class"][] = 'bTiles__item';
        }
        $vars['title'] = $node->get('title')->value;

        if (($view_mode == 'full') || ($view_mode == 'home') || ($view_mode == 'teaser')) {
          $room = (!empty($vars["content"]["field_comt_evt_room_reference"]) &&
            !empty($vars["content"]["field_comt_evt_room_reference"][0])) ?
            $vars["content"]["field_comt_evt_room_reference"][0] : '';
          if (!empty($room)) {
            $room_url = $room['#url']->toString();
            $room_url = Url::fromUserInput($room_url);
            $vars['room_link'] = Link::fromTextAndUrl($room["#title"], $room_url);
            $vars['room_url'] = $room_url;
          }
        }

        $vars['back_link'] = [
          '#type' => 'link',
          '#title' => t('back'),
          '#url' => Url::fromUserInput('/committees'),
          '#attributes' => [
            'class' => ['btn', 'btn_a', 'section__btnBack', 'section__btnBack_b'],
          ],
        ];
        break;
      case 'subcommittee':
        $commitee = (!empty($vars["content"]["field_subcomt"]) &&
          !empty($vars["content"]["field_subcomt"]['#items'])) ?
          $vars["content"]["field_subcomt"]['#items']->getValue() : '';
        if (!empty($commitee) && !empty($commitee[0])) {
          $tid = !empty($commitee[0]["target_id"]) ? $commitee[0]["target_id"] : '';
          $tree = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
            ->loadTree('committees', $tid, NULL, FALSE);
          $tids = [];
          foreach ($tree as $term) {
            $tids[] = $term->tid;
          }
          $params = implode(',', $tids);
          $params = [$params];
          $vars['dropdown'] = _senate_get_view('committee_dropdown', 'block_1', $params);
          $vars['senators'] = _senate_get_view('senators', 'block_1', [$tid]);
          $url = Url::fromUserInput('/senators');
          $options = ['class' => ['btn']];
          $url->setOption('attributes', $options);
          $url->setOption('query', ['committee' => $tid]);
          $vars['all_members'] = Link::fromTextAndUrl(t('see all members'), $url);

          if (empty($tids)) {
            $vars['committee_events_title'] = t('Upcoming Events');
            $vars['committee_events'] = _senate_get_view('subcommittee_events', 'block_1', [$tid]);
          }
          else {
            $params[0] = $tid . ',' . $params[0];
            $vars['committee_events_title'] = t('Subcommittee Events');
            $vars['committee_events'] = _senate_get_view('committee_events', 'block_1', $params);
          }

          $term_obj = Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);
          if (!empty($term_obj)) {
            if ($term_obj->hasField('field_comt_icon')) {
              $icon_field = $term_obj->get('field_comt_icon');
              if (!empty($icon_field->entity)) {
                $vars['icon'] = file_create_url($icon_field->entity->getFileUri());
              }
            }
            if ($term_obj->hasField('field_comt_icon_2x')) {
              $icon_field = $term_obj->get('field_comt_icon_2x');
              if (!empty($icon_field->entity)) {
                $vars['icon_2x'] = file_create_url($icon_field->entity->getFileUri());
              }
            }
          }

          $vars['press_releases'] = _senate_get_view('subcmt_up_press_rels', 'block_1', $params);
          $vars['subcommittee_agencies'] = _senate_get_view('subcommittee_agencies', 'block_1', [$tid]);
        }
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;
      case 'senator':
        $district = (!empty($vars["content"]["field_senator_district_taxonomy"]) &&
          !empty($vars["content"]["field_senator_district_taxonomy"]['#items'])) ?
          $vars["content"]["field_senator_district_taxonomy"]['#items']->getValue() : '';

        if (!empty($district) && !empty($district[0])) {
          $tid = !empty($district[0]["target_id"]) ? $district[0]["target_id"] : '';
          $term_obj = Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->load($tid);
          if (!empty($term_obj)) {
            if ($term_obj->hasField('field_district_term_map_file')) {

              $file = $term_obj->get('field_district_term_map_file');
              if (!empty($file->entity)) {
                $file_url = file_create_url($file->entity->getFileUri());
                $vars['file'] = Markup::create("<a href='$file_url' target='_blank'><i class=\"ss-icon ss-glyphish-outined ss-map\"></i>see map</a>");
              }
            }
          }
//          $vars['news_block'] = _senate_get_view('week_review', 'block_1');

//          $uid = $node->getOwnerId();
//          $vars['news_block'] = _senate_get_view('senator_recent_news', 'block_1', [$uid]);
        }
        if (!empty($vars['content']['field_senator_video_link_video']) &&
          !empty($vars['content']['field_senator_video_link_video']['#items'])) {
          $items = $vars['content']['field_senator_video_link_video']['#items'];
          $value = !empty($items) ? $items->getValue() : '';
          if (!empty($value)) {
            $url = $value[0]['value'];
            $video_data = _get_youtube_embed_data($url, ['rel' => 0, 'controls' => 0, 'showinfo' => 0, 'enablejsapi' => 1]);
            $vars['video_id'] = !empty($video_data['video_id']) ? $video_data['video_id'] : '';
            $vars['video_url'] = !empty($video_data['url']) ? $video_data['url'] : '';
          }

          $img_file_uri = $theme_path . '/dist/images/default-video-preview.jpg';
          if (!empty($vars['content']['field_video_preview_image'][0]['#item'])){
            $img_file_uri = $vars['content']['field_video_preview_image'][0]['#item']->entity->url();
          }
          $vars['preview_image'] = Markup::create("<span class=\"bMedia__preview\" style=\"background-image: url('$img_file_uri')\"></span>");
        }
        if (!empty($vars['content']['field_senator_photo'][0]['#item'])){
          $senator_photo_uri = $vars['content']['field_senator_photo'][0]['#item']->entity->url();
        }
        $vars['senator_photo_download'] = !empty($senator_photo_uri) ? $senator_photo_uri : '';
        $photo_download_array = explode('/', $vars['senator_photo_download']);
        $vars['senator_photo_download_target'] = !empty($vars['senator_photo_download']) ? end($photo_download_array) : '';

        $vars['nid'] = $node->id();
        $title = $node->getTitle();
        $title = trim($title);
        $title = strtolower($title);
        $vars['title_alias'] = str_replace(' ', '-', $title);
        break;
      case 'reports':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;

      case 'session_summary':
        if (!empty($vars['content']['field_session_summary_year_date'][0]['#text'])){
          $vars['summary_id'] = Markup::create("overview-" . $vars['content']['field_session_summary_year_date'][0]['#text']);
        }
        break;
      case 'week_review':
        $vars['title'] = $node->getTitle();
        _senate_add_share_this($vars);
        $vars['back_link'] = [
          '#type' => 'link',
          '#title' => t('back to week in review'),
          '#url' => Url::fromUserInput('/news'),
          '#attributes' => [
            'class' => ['btn', 'btn_a', 'section__btnBack'],
          ],
        ];
        break;
      case 'press_release':

        $vars['title'] = $node->getTitle();
        $vars['url_with_back_param'] = Url::fromRoute(
          'entity.node.canonical', ['node' => $node->id()],
          ['query' => ['back' => \Drupal::destination()->get()]]
        );

        $vars['back_link'] = [
          '#type' => 'link',
          '#title' => t('back to press releases'),
          '#url' => Url::fromUserInput('/press-releases'),
          '#attributes' => [
            'class' => ['btn', 'btn_a', 'section__btnBack'],
          ],
        ];

        if (!empty(\Drupal::request()->get('back'))
          && strpos(\Drupal::request()->get('back'), '/press-releases-audio') !== FALSE
        ) {
          $vars['back_link']['#title'] = t('back to audio');
          $vars['back_link']['#url'] = Url::fromUserInput(\Drupal::request()->get('back'));
        } else if (!empty(\Drupal::request()->get('back'))
          && strpos(\Drupal::request()->get('back'), '/press-releases') !== FALSE
        ) {
          $vars['back_link']['#url'] = Url::fromUserInput(\Drupal::request()->get('back'));
        }

      _senate_add_share_this($vars);
      break;
      case 'publications':
        if ($node->id() == SENATE_CONTACTS_LANDING_NID) {
          $vars['leadersip'] = _senate_get_block('leadership');
        }
        break;
      case 'cl_app_bud':
      case 'cl_jnt_cnf':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;
      case 'calendar':
        $vars['latest_st_journals'] = _senate_get_view('calendar_lt_st_journals', 'block_1');
        $vars['latest_joint_app'] = _senate_get_view('calendar_lt_joint_app_bd', 'block_1');
        break;
      case 'edu_indiv_art_work':
        if ($vars["view_mode"] == 'teaser') {
          $vars['title'] = $node->label();
        }
        else {
          $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        }
        break;
      case 'senate_votes':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');

        $vars['votes'] = _senate_get_block('views_block__senate_votes_inner_block_1');
        break;
      case 'history':
      case 'meeting_notice':
      case 'contacts_ada':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;
      case 'contact':
      case 'contact_reservation':
      case 'protem_podcast':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;
      case 'senate_studies':
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        $year = !empty($vars["content"]["field_senate_studies_year"]) &&
          !empty($vars["content"]["field_senate_studies_year"]["#items"]) ?
          $vars["content"]["field_senate_studies_year"]["#items"]->get(0)->value : '';
        $vars['interim_studies'] = _senate_get_view('senate_studies', 'block_1', ['all']);

        $vars['sub_menu'] = _senate_get_block('senatestudiessubmenu');
        break;
      case 'tables_page':
        $vars['sub_menu'] = _senate_get_block('senatestudiessubmenu');
        break;
      case 'senator_blog_post':
        _senate_add_share_this($vars);

        $uid = $node->getOwnerId();
        $senator_data = _senate_get_senators_name($uid);
        $main_nid = key($senator_data);
        $name = !empty($senator_data[$main_nid]) ? $senator_data[$main_nid] : '';
        $name_arr = explode(' ', $name);
        $second_name = end($name_arr);
        $vars['back_link'] = [
          '#type' => 'link',
          '#title' => t('back to senator @name’s news', ['@name' => $second_name]),
          '#url' => Url::fromUserInput(SENATE_SENATOR_RECENT_NEWS_URL . '/' . $uid),
          '#attributes' => [
            'class' => ['btn', 'btn_a', 'section__btnBack'],
          ],
        ];

        $vars['bg_image'] = !empty($vars["content"]["field_senator_blog_post_image"]) &&
          !empty($vars["content"]["field_senator_blog_post_image"]["#items"]) ?
          $vars["content"]["field_senator_blog_post_image"]["#items"]->entity->url() : '';
        break;
      case 'gallery' :
        $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
        break;
    }
  }
}

/**
 * Implements hook_theme_suggestions_taxonomy_term_alter().
 */
function senate_theme_suggestions_taxonomy_term_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\taxonomy\TermInterface $term */
  $term = $variables['elements']['#taxonomy_term'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');
  // Add view mode theme suggestions.
  $suggestions[] = 'taxonomy_term__' . $sanitized_view_mode;
  $suggestions[] = 'taxonomy_term__' . $term->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'taxonomy_term__' . $term->id() . '__' . $sanitized_view_mode;
}

/**
 * @param array $vars
 */
function _senate_add_share_this(array &$vars) {
  $path_to_theme = base_path() . drupal_get_path('theme', 'senate');
  if (!empty($vars["content"]["sharethis"])
    && !empty($vars["content"]["sharethis"]["#content"])
  ) {
    $sharethis = [
      '#theme' => 'senate_news_sharethis',
      '#url' => $vars["content"]["sharethis"]["#content"]["m_path"],
      '#title' => $vars["content"]["sharethis"]["#content"]["m_title"],
      '#current_path' => $path_to_theme,
    ];
    $vars["content"]["sharethis"]["#content"]["st_spans"] = render($sharethis);
  }
}

/**
 * Implements hook_preprocess_field().
 */
function senate_preprocess_field(array &$vars, $hook) {
  global $base_path;

  $view_mode = !empty($vars["element"]["#view_mode"]) ? $vars["element"]["#view_mode"] : '';
  $disable_quick_edit_field_types = [
    'image',
    'link',
    'field_collection',
    'entity_reference_revisions'
  ];

  if (in_array($vars['field_type'], $disable_quick_edit_field_types)) {

    if (isset($vars['attributes']['data-quickedit-field-id'])) {
      unset($vars['attributes']['data-quickedit-field-id']);
    }
  }

  if ($vars['field_type'] == 'image') {
    if (!empty($vars['items'][0]['content']['#item']->entity)) {
      if (!empty($vars["items"][0]["content"]["#image_style"])) {
        $style = $vars["items"][0]["content"]["#image_style"];
        $img_file_uri = $vars['items'][0]['content']['#item']->entity->getFileUri();
        $vars['image_url'] = ImageStyle::load($style)->buildUrl($img_file_uri);
      }
      else {
        $vars['image_url'] = $vars['items'][0]['content']['#item']->entity->url();
      }
    }
  }

  switch ($vars['element']['#field_name']) {
    case 'field_senator_committee_taxonomy':

      $commitees = (!empty($vars['items'])) ? $vars['items']: '';
      if (!empty($commitees)){
        foreach ($commitees as $key=> $item) {
          $tid = !empty($item['content']['#plain_text']) ? $item['content']['#plain_text'] : '';
          $term_obj = Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->load($tid);
          if (!empty($term_obj)) {
            if ($term_obj->hasField('field_link_to_committee_page')) {
              $commitee_link = $term_obj->get('field_link_to_committee_page')
                ->getValue();
              $url = Url::fromUri('internal:#');
              if (!empty($commitee_link[0]['uri'])) {
                $url = Url::fromUri($commitee_link[0]['uri']);
              }
              $options = ['class' => ['bMembership__item',], 'target' => ['_blank']];
              $url->setOption('attributes', $options);
              $title = $term_obj->get('name')->getValue();
              $vars['items'][$key]['term_url'] = Link::fromTextAndUrl($title[0]['value'], $url);
            }
          }
        }
      }
      break;
    case 'field_home_slider_bg_image_mob':
      $vars['img_classes'] = ['section__bg_mobile'];
      break;
    case 'field_home_finder_left_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('btn');
        $vars['items'][$key]['wrappers'] = 'sFinder__btn-wrap';
      }
      break;
    case 'field_senator_ext_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('btn');
      }
      break;
    case 'field_leadership_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('btn');
        $vars['items'][$key]['wrappers'] = 'sLead__btnWrap';
      }
      break;
    case 'field_footer_find_senator_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('btn');
        $vars['items'][$key]['wrappers'] = 'sFooter__btnWr';
      }
      break;
    case 'field_senator_address_txt':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['wrappers'] = 'bSenBio__address';
      }
      break;

    case 'field_senator_social_inst_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
//        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('bSoc__ico ss-icon ss-social-circle ss-instagram');
        $vars['items'][$key]['wrappers'] = 'bSoc__item bSoc__item_instagram';
        $vars['items'][$key]['content']['#title'] = "instagram";
      }
      break;

    case 'field_senator_social_fb_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
//        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('bSoc__ico ss-icon ss-social-circle ss-facebook');
        $vars['items'][$key]['wrappers'] = 'bSoc__item bSoc__item_facebook';
        $vars['items'][$key]['content']['#title'] = "facebook";
      }
      break;
    case 'field_senator_social_tw_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
//        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('bSoc__ico ss-icon ss-social-circle ss-twitter');
        $vars['items'][$key]['wrappers'] = 'bSoc__item bSoc__item_twitter';
        $vars['items'][$key]['content']['#title'] = "twitter";

      }
      break;
    case 'field_comt_evt_room_reference':
    case 'field_comt_sched_event_room_ref':
      $node = !empty($vars["element"]["#object"]) ? $vars["element"]["#object"] : '';
      $nid = !empty($node) ? $node->id() : '';
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['content']['#options']['attributes']['class'] = array('bTiles__btn btn btn_b');
        $vars['items'][$key]['content']['#options']['attributes']['target'] = array('_blank');

        if ($vars['element']['#field_name'] == 'field_comt_evt_room_reference') {
          $vars['items'][$key]['content']['#options']['attributes']['data-nid'] = $nid;
          $vars['items'][$key]['content']['#options']['attributes']['class'][] = 'events_custom_timetable';

          if (($view_mode == 'home') || ($view_mode == 'teaser')) {
            $vars['items'][$key]['content']['#options']['attributes']['class'] = [];
            $vars['items'][$key]['content'] = !empty($vars['items'][$key]['content']['#title']) ?
              Markup::create($vars['items'][$key]['content']['#title']) : '';
          }
        }
      }
      break;
    case 'field_footer_find_senator_image':
    case 'field_leadership_logo_image':
    case 'field_home_finder_left_image':
    case 'field_home_finder_right_image':
    case 'field_webform_block_icon':
    case 'field_basic_top_logo_image':
    case 'field_contact_top_logo':
    case 'field_par_publications_page_icon':
    case 'field_menu_icon':
    case 'field_calendar_up_ddl_icon':
    case 'field_home_top_slider_icon':
    case 'field_contacts_ada_wheel_icon':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $image_url = $vars['items'][$key]['content']['#item']->entity->url();
        $vars['items'][$key]['content']['image_url'] = $image_url;
      }

      if (!empty($vars['items'])) {
        $image_srcset = '';
        $image_src = $vars['items'][0]['content']['image_url'];
        if (!empty($vars['items'][1])) {
          $image_srcset = 'srcset="' . $vars['items'][1]['content']['image_url'] . ' 2x"';
        }
        $image_html = '<img src="' . $image_src . '"  ' . $image_srcset . ' alt="">';
        $vars['img_src'] = Markup::create($image_html); //prepared image for render
      }

      break;
    case 'field_contacts_paragraph_slider':
      $vars['elements'] = array();
      $style = 'rockdevels_defaults_imagemagick';
      $thumb_style = 'custom_contact_slider';

      $elements = _rows_from_paragraphs($vars, array(
        'field_contacts_par_sli_image',
        'field_contacts_par_sli_thumb_img',
      ));
      foreach ($elements as $key => $row) {
        $image = '';
        $thumb = '';
        if (!empty($row['field_contacts_par_sli_image'][0]['uri'])) {
          $image = ImageStyle::load($style)
            ->buildUrl($row['field_contacts_par_sli_image'][0]['uri']);
          $thumb = ImageStyle::load($thumb_style)
            ->buildUrl($row['field_contacts_par_sli_image'][0]['uri']);
        }
        $vars['elements'][$key]['large_img'] = $image;
        $vars['elements'][$key]['thumb_img'] = $thumb;
      }
      break;
    case 'field_home_tiles_paragraph':
      $vars['elements'] = array();
      $style = 'rockdevels_defaults_imagemagick';

      $elements = _rows_from_paragraphs($vars, array(
        'field_paragraph_tiles_image',
        'field_paragraph_tiles_link',
      ));

      foreach ($elements as $key => $row) {
        $img_markup = '';
        if (!empty($row['field_paragraph_tiles_image'][0]['uri'])) {
          $image_srcset = '';
          $image_src = ImageStyle::load($style)
            ->buildUrl($row['field_paragraph_tiles_image'][0]['uri']);
          if (!empty($row['field_paragraph_tiles_image'][1]['uri'])) {
            $image_srcset = ' srcset="' . ImageStyle::load($style)
                ->buildUrl($row['field_paragraph_tiles_image'][1]['uri']) . ' 2x"';
          }

          $img_src = '<span class="bTiles__ico"><img src="' . $image_src . '"  ' . $image_srcset . ' alt=""></span>';
          $img_markup = Markup::create($img_src); //prepared image for render
        }

        $link_title_text = !empty($row['field_paragraph_tiles_link'][0]['title']) ? $row['field_paragraph_tiles_link'][0]['title'] : '';
        $link_title = "<span class=\"bTiles__title\">" . $link_title_text . "</span>";

        $markup = Markup::create($img_markup . $link_title); //prepared content for render

        $url = Url::fromUri($row['field_paragraph_tiles_link'][0]['uri']);
        $options = !empty($row["field_paragraph_tiles_link"][0]["options"]) &&
          !empty($row["field_paragraph_tiles_link"][0]["options"]["attributes"]) ?
          $row["field_paragraph_tiles_link"][0]["options"]["attributes"] : [];
        $options['class'] = ['bTiles__item'];
        $url->setOption('attributes', $options);

        $vars['elements'][$key]['element'] = Link::fromTextAndUrl($markup, $url);
      }
      break;
    case 'field_comt_sched_event_room':
      if (!empty($vars["items"]) && !empty($vars["items"][0])) {
        $vars["items"][0]["content"]["#options"]["attributes"] = ['class' =>
          ['bListItems__btn', 'btn', 'btn_b']
        ];
        $title = $vars["items"][0]["content"]["#title"];
        $vars["items"][0]["content"]["#title"] = Markup::create('<span><span>•</span></span> ' . $title);
      }
      break;
    case 'field_comt_evt_room':
      if (!empty($vars["items"]) && !empty($vars["items"][0])) {
        $vars["items"][0]["content"]["#options"]["attributes"] = ['class' =>
          ['bTiles__btn', 'btn', 'btn_b', 'btn_b_live']
        ];
        $title = $vars["items"][0]["content"]["#title"];
        $vars["items"][0]["content"]["#title"] = Markup::create('<span><span>•</span></span> ' . $title);
      }
      break;
    case 'field_subcomt_app_title':
    case 'field_education_seats':
    case 'field_education_democrat':
    case 'field_education_republican':
    case 'field_education_vacant_seats':
    case 'field_home_top_slider_title':
      if (!empty($vars['items'])) {
        $vars["items"][0]["content"]["#template"] = '{{ value|raw }}';
      }
      break;
    case 'field_agencies_doc_doc':
    case 'field_reports_files':
    case 'field_session_summary_file':
    case 'field_meeting_notice_files':
    case 'field_comt_evt_files':
      $items = !empty($vars["items"]) ? $vars["items"] : [];
      $vars['files'] = [];
      foreach ($items as $key => $item) {
        if (!empty($item["content"]["#file"])) {
          $vars['files'][$key]['url'] = file_create_url($item["content"]["#file"]->getFileUri());
          $vars['files'][$key]['title'] = !empty($item["content"]["#description"]) ? $item["content"]["#description"] : '';
        }
      }
      break;

    case 'field_financials_files':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $title = Xss::filter(html_entity_decode($item["content"]["#description"]));
        $title = !empty($title) ? $title : t('Download');
        $title = Markup::create('<span class="bTiles__title">' . $title . '</span><span class="bTiles__btnWrap"><span class="btn btn_a btn_s_c">view pdf</span></span>');
        $file = $item["content"]["#file"];
        if (!empty($file)) {
          $url = $file->url();
          $url = Url::fromUri($url);
          $options = ['class' => ['bTiles__item',]];
          $options['target'] = '_blank';

          $url->setOption('attributes', $options);
          $vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
        }
      }
      break;
    case 'field_cl_app_budget_file':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $title = Xss::filter(html_entity_decode($item["content"]["#description"]));
        $title = !empty($title) ? $title : t('Download');
        $file = $item["content"]["#file"];
        if (!empty($file)) {
          $url = $file->url();
          $url = Url::fromUri($url);
          $options = ['class' => ['btn', 'btn_b', 'btn_s_a']];
          $options['target'] = '_blank';

          $url->setOption('attributes', $options);
          $vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
        }
      }
      break;
    case 'field_table_cell_file':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $title = Xss::filter(html_entity_decode($item["content"]["#description"]));
        $title = !empty($title) ? $title : t('Download');
        $file = $item["content"]["#file"];
        if (!empty($file)) {
          $url = $file->url();
          $url = Url::fromUri($url);
          $options['target'] = '_blank';
          $options['download'] = $title;

          $url->setOption('attributes', $options);
          $vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
        }
      }
      break;
    case 'field_menu_link':
    case 'field_edu_indiv_art_work_btn':
    case 'field_education_gallery_artwork':
    case 'field_home_top_slider_link':
      if (!empty($vars["items"]) && !empty($vars["items"][0])) {
        $vars["items"][0]["content"]["#options"]["attributes"] = [
          'class' => ['btn']
        ];
      }
      break;
    case 'field_historical_members':
			$items = !empty($vars['items']) ? $vars['items'] : [];
			foreach ($items as $key => $item) {
				$title = Xss::filter(html_entity_decode($item["content"]["#description"]));
				$title = !empty($title) ? $title : t('see historical members');
				$file = $item["content"]["#file"];
				if (!empty($file)) {
					$url = $file->url();
					$url = Url::fromUri($url);
					$options = ['class' => ['btn', 'btn_a']];
					$options['target'] = '_blank';
					$url->setOption('attributes', $options);
					$vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
				}
			}
      break;
    case 'field_calendar_up_ddl_date':
      if (!empty($vars['items']) && !empty($vars["items"][0])) {
        $vars["date"] = $vars["items"][0]["content"]["#text"];
      }
      break;
    case 'field_tables_page_revised_date':
      if (!empty($vars['items']) && !empty($vars["items"][0])) {
        $vars['date_revised'] = "Revised:" .  $vars["items"][0]["content"]["#markup"];
      }
      break;
    case 'field_glossary_terms':
      $node = !empty($vars["element"]["#object"]) ? $vars["element"]["#object"] : '';
      if (!empty($node)) {
        $letter = $node->hasField('field_glossary_letter') ?
          $node->field_glossary_letter->get(0)->value : '';
        $vars['id'] = 'item-' . strtolower($letter);
        $vars['letter'] = strtolower($letter);
      }
      break;
    case 'field_senate_votes_action_file':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $title = Xss::filter(html_entity_decode($item["content"]["#description"]));
        $title = !empty($title) ? $title : t('Download');
        $file = $item["content"]["#file"];
        if (!empty($file)) {
          $url = $file->url();
          $url = Url::fromUri($url);
          $options = ['class' => ['bTb__text', 'bTb__text_a', 'pageIn_cl_c']];
          $options['target'] = '_blank';

          $url->setOption('attributes', $options);
          $vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
        }
      }
      break;
    case 'field_contacts_ada_wheel_files':
    case 'field_contacts_ada_info_file':
    case 'field_issue_files':
    $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $title = Xss::filter(html_entity_decode($item["content"]["#description"]));
        $title = !empty($title) ? $title : t('View file');
        $file = $item["content"]["#file"];
        if (!empty($file)) {
          $url = $file->url();
          $url = Url::fromUri($url);
          $options = ['class' => ['bListLinks__link']];
          $options['target'] = '_blank';

          $url->setOption('attributes', $options);
          $vars['items'][$key]['content'] = Link::fromTextAndUrl($title, $url);
        }
      }
      break;
    case 'field_senate_votes':
      $items = !empty($vars["items"]) ? $vars["items"] : [];
      $pr_ids = [];
      foreach ($items as $key => $item) {
        if (!empty($item["content"]["#paragraph"])) {
          $pr_ids[$key] = $item["content"]["#paragraph"]->id();
        }
      }
      $grouped_items = _senate_votes_get_grouped_items($pr_ids);
      $vars['groups'] = [];
      foreach ($grouped_items as $key => $gr_items) {
        foreach ($gr_items as $gr_item) {
          $vars['groups'][$key][] = array_search($gr_item, $pr_ids);
        }
      }
      break;
    case 'field_education_senate_history':
    case 'field_education_find_bills':
    case 'field_education_contact':
    case 'field_education_leg_terms':
      if (!empty($vars["items"]) && !empty($vars["items"][0])) {
        $vars['url'] = $vars["items"][0]["content"]["#url"]->toString();
        $vars['title'] = $vars["items"][0]["content"]["#title"];
      }
      break;
    case 'field_home_top_slider':
      $vars['bg_images'] = [];
      $vars['turn_on'] = [];
      $bg_images = _rows_from_paragraphs($vars, ['field_home_top_slider_bg_img', 'field_home_top_slider_turn_on']);
      foreach ($bg_images as $key => $value) {
        $bg_img = !empty($value["field_home_top_slider_bg_img"]) && !empty($value["field_home_top_slider_bg_img"][0]) ?
          $value["field_home_top_slider_bg_img"][0]["value"] : '';
        $turn_on = !empty($value["field_home_top_slider_turn_on"]) && !empty($value["field_home_top_slider_turn_on"][0]) ?
          $value["field_home_top_slider_turn_on"][0]["value"] : '';
        if (!empty($bg_img)) {
          $vars['bg_images'][$key] = $bg_img;
        }
        if (!empty($turn_on)) {
          $vars['turn_on'][] = $key;
        }
      }
      break;
    case 'field_senator_social_linkin_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars['items'][$key]['wrappers'] = 'bSoc__item bSoc__item_linkedin';
        $vars['items'][$key]['content']['#title'] = "linkedin";
      }
      break;

    case 'field_issue_links':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars["items"][$key]["content"]["#options"]["attributes"] = ['class' => 'bListLinks__link'];
      }
      break;
    case 'field_basic_back_button_link':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars["items"][$key]["content"]["#options"]["attributes"] = ['class' => 'btn btn_a section__btnBack'];
      }
      break;
    case 'field_meeting_notice_date':
    case 'field_comt_evt_date':
      $date = !empty($vars["element"]["#items"]) ? $vars["element"]["#items"]->get(0)->value : [];
      if (!empty($date)) {
        $utc_timezone = new \DateTimeZone('UTC');
        $site_timezone = new DateTimeZone(date_default_timezone_get());
        $date_obj = new DrupalDateTime($date, $utc_timezone);
        $date_obj->setTimezone($site_timezone);
        $vars['time'] = $date_obj->format('g:ia');
      }
      break;
    case 'field_senate_studies_links':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars["items"][$key]["content"]["#options"]["attributes"] = ['class' =>
          ['btn', 'btn_s_f']
        ];
      }
      break;
    case 'field_meeting_notice_pres_rep':
      $available = !empty($vars["element"]["#items"]) ?
        $vars["element"]["#items"]->get(0)->value : '';
      if ($available == 'Available') {
        $parent_nid = $vars["element"]["#object"]->id();
        $alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $parent_nid);
        $vars["items"][0]["content"]["#markup"] = '<a href="' . $alias . '" class="pageIn_cl_a">' . $vars["items"][0]["content"]["#markup"] . '</a>';
      }
      elseif ($available == 'Not Available') {
        $vars["items"][0]["content"]["#markup"] = '<span class="pageIn_cl_b">' . $vars["items"][0]["content"]["#markup"] . '</span>';
      }
      break;
    case 'field_live_stream_iframe':
    case 'field_live_stream_voting':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $iframe = Xss::filter(html_entity_decode($item["content"]["#context"]["value"]), ['iframe']);
        $vars["items"][$key]["content"]["#context"]["value"] = $iframe;
        $vars["items"][$key]["content"]["#template"] = '{{ value|raw }}';
      }
      break;
    case 'field_rooms_rooms':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars["items"][$key]["content"]["#options"]["attributes"] = ['class' =>
          ['btn', 'btn_b']
        ];
        $title = $vars["items"][$key]["content"]["#title"];
        $vars["items"][$key]["content"]["#title"] = Markup::create('<span><span>•</span></span> ' . $title);
      }
      break;
    case 'field_pro_tem_par_video':
        $items = $vars['element']['#items'];
        $value = !empty($items) ? $items->getValue() : '';
        if (!empty($value)) {
          $url = $value[0]['value'];
          $video_data = _get_youtube_embed_data($url, ['rel' => 0, 'controls' => 0, 'showinfo' => 0, 'enablejsapi' => 1]);
          $vars['video_id'] = !empty($video_data['video_id']) ? $video_data['video_id'] : '';
        }
      break;
    case 'field_slider_image':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      $vars['bg_images'] = [];
      foreach ($items as $key => $item) {
        if (!empty($item['content']['#item']->entity)) {
          if (!empty($item["content"]["#image_style"])) {
            $style = $item["content"]["#image_style"];
            $img_file_uri = $item['content']['#item']->entity->getFileUri();
            $vars['bg_images'][$key] = ImageStyle::load($style)->buildUrl($img_file_uri);
          }
          else {
            $vars['bg_images'][$key] = $item['content']['#item']->entity->url();
          }
        }
      }
      break;
    case 'field_cl_jnt_cnf_file':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      foreach ($items as $key => $item) {
        $vars["items"][$key]["content"]["#options"]["attributes"] = ['class' =>
          ['btn', 'btn_b', 'btn_s_a']
        ];
      }
      break;
    case 'field_comt_evt_agenda':
      $items = !empty($vars['items']) ? $vars['items'] : [];
      $items_amount = count($items);
      if ($items_amount < 2) {
        $vars["multiple"] = FALSE;
      }
      break;
  }
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function senate_theme_suggestions_field_alter(array &$suggestions, array $vars) {
  $element = $vars['element'];
  $suggestions[] = 'field__' . $element['#field_name'] . '__' . $element['#view_mode'];

  switch ($vars['element']['#field_name']) {
    case 'field_block_navigation_links':
    case 'field_leadership_name_txt':
    case 'field_leadership_post_txt':
    case 'field_subcomt_mmb_position':
    case 'field_publications_column_text':
    case 'field_publications_column_title':
    case 'field_no_meetings_text':
      $suggestions[] = 'field__no_wrappers';
      break;

    case 'field_home_top_bg_image':
    case 'field_leadership_bg_image':
    case 'field_home_section_image':
    case 'field_home_slider_bg_image':
    case 'field_basic_top_image':
      $suggestions[] = 'field__bg_image';
      break;

    case 'field_home_finder_left_link':
    case 'field_footer_find_senator_link':
    case 'field_leadership_link':
    case 'field_senator_social_fb_link':
    case 'field_senator_social_inst_link':
    case 'field_senator_social_tw_link':
    case 'field_senator_address_txt':
    case 'field_senator_social_linkin_link':
      $suggestions[] = 'field__with_custom_wrapper';
      break;

    case 'field_footer_find_senator_image':
    case 'field_leadership_logo_image':
    case 'field_home_finder_right_image':
    case 'field_home_finder_left_image':
    case 'field_webform_block_icon':
    case 'field_contacts_ada_wheel_icon':
    case 'field_par_publications_page_icon':
      $suggestions[] = 'field__src_srcset_images';
      break;
    case 'field_cl_jnt_cnf_adop_opp_ch':
    case 'field_cl_jnt_cnf_adop_ch_orgn':
      $suggestions[] = 'field__paragraph__field_cl_jnt_cnf_sub_ch_orgn';
      break;
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function senate_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['keys']['#attributes']['placeholder'] = t('search here');
    $form["#cache"]["contexts"][] = 'url.path';
  }
  if ($form_id == 'search_api_page_block_form_find_legislation') {
    $form['keys']['#attributes']['placeholder'] = t('Enter Bill Number');
  }

  if ($form_id == 'user_login_form' ) {
    // Add placeholders.
    $form['actions']['submit']['#attributes']['class'][] = 'testtest';

  }

  if (!empty($form["elements"]) && !empty($form["elements"]["captcha"])) {
    $form["elements"]["captcha"]["#pre_render"][] = 'senate_change_captcha_description';
  }

  switch ($form_id) {
    case 'webform_submission_reserve_a__node_10594_add_form':
      $form['elements']['date_fieldset']['date']['#attributes']['placeholder'] = 'Start Day';
      $form['elements']['date_fieldset']['end_time']['#attributes']['placeholder'] = 'End Day';
      $form['elements']['date_fieldset']['date']['#date_time_format'] = 'h:i a';
      $form['elements']['date_fieldset']['end_time']['#date_time_format'] = 'h:i a';
      break;
    case 'views_exposed_form':
      $storage = $form_state->getStorage();
      $view = !empty($storage["view"]) ? $storage["view"] : '';
      $view_name = !empty($view) ? $view->id() : '';

      if ($view_name == 'agencies_documents') {
        $tid = !empty($view->args) ? $view->args : '';
        $tid = !empty($tid[1]) ? $tid[1] : '';
        $years = _senate_get_years_existing_nodes($tid);
        if (!empty($form["year"])) {
          foreach ($form["year"]["#options"] as $key => $value) {
            if (($key !== 'All') && (!in_array($key, $years))) {
              unset($form["year"]["#options"][$key]);
            }
          }
        }
      }
      elseif ($view_name == 'senators') {
        $committee_options = (!empty($form["committee"]) && !empty($form["committee"]["#options"])) ?
          $form["committee"]["#options"] : [];
        $options = _senate_get_committee_options($committee_options);
        if (!empty($options)) {
          $form["committee"]["#options"] = $options;
        }
        if (!empty($form["zip"])) {
          $form["zip"]["#placeholder"] = t('Enter Zip');
        }
      }
      elseif ($view_name == 'journals') {
        $data = _senate_get_journals_options();
        $form['#attached']['drupalSettings']['senate']['active_dates'] = $data['dates'];

        $form['field_journals_files_date_value']['#attributes']['readonly'] = true;
        $form["#attributes"]["class"][] = 'form bSelect bSelect_filter bSelect_a bSelect_gap_b bSelect_date';
      }
      elseif ($view_name == 'search_statutes_constitutions') {
        if (!empty($form["constitutions"])) {
          $form["constitutions"]['#placeholder'] = t('Search by keyword(s)');
          $form['constitutions_submit'] = [
            '#type' => 'submit',
            '#button_type' => 'primary',
            '#value' => 'constitutions_submit',
          ];
        }
        if (!empty($form["statutes"])) {
          $form["statutes"]['#placeholder'] = t('Search by keyword(s)');
        }
      }
      elseif ($view_name == 'senate_staff') {
        $form["#attributes"]["class"][] = 'bSelect bSelect_a bSelect_filter bSelect_filter_a bSelect_inline bSelect_size_b bSelect_gap_a';

        if (!empty($form["division"])) {
          $options = _senate_get_staff_options();
          $division_options = array_combine($options, $options);
          $division_options = array_merge(['' => t('Showing All')], $division_options);

          $form["division"] = [
            '#type' => 'select',
            '#options' => $division_options,
            '#default_value' => '',
          ];
        }
      }
      elseif ($view_name == 'senate_votes_inner') {
        $nid = !empty($view->args) ? $view->args : '';
        $nid = !empty($nid[0]) ? $nid[0] : '';

        if (empty($nid)) {
          $node = \Drupal::routeMatch()->getParameter('node');
          $nid = !empty($node) && is_object($node) ? $node->id() : '';
        }

        $form["#attributes"]["class"][] = 'form-inline';
        if (!empty($form["measure"]) && !empty($nid)) {
          $options = _senate_get_votes_measure_options($nid);
          $measure_options = array_combine($options, $options);
          $measure_options = array_merge(['' => t('Showing All')], $measure_options);

          $form["measure"] = [
            '#type' => 'select',
            '#options' => $measure_options,
            '#default_value' => '',
          ];
        }
        if (!empty($form["author"]) && !empty($nid)) {
          $options = _senate_get_votes_author_options($nid);
          $author_options = array_combine($options, $options);
          $author_options = array_merge(['' => t('Showing All')], $author_options);

          $form["author"] = [
            '#type' => 'select',
            '#options' => $author_options,
            '#default_value' => '',
          ];
        }
      }
      break;
  }

  if (strpos($form_id, 'webform_submission_sign_up_committee_meeting_node') !== FALSE) {
    if (!empty($form["elements"]["committees"])) {
      $options = $form["elements"]["committees"]["#options"];
      $form["elements"]["committees"]["#options"] = ['all' => t('Receive notifications for all committees')] + $options;
      $form["#validate"][] = 'webform_sign_up_committee_meeting_validate';
    }
  }
}

/**
 * Creates a simple text rows array from a paragraphs, to be used in a
 * field_preprocess function.
 *
 * @param $vars
 * An array of variables to pass to the theme template.
 * @param $field_array
 * Array of fields to be turned into rows in the field collection.
 * @return array
 */
function _rows_from_paragraphs(&$vars, $field_array) {
  $rows = array();
  if (!empty($vars['element']['items'])) {
    $items = $vars['element']['items'];
  }
  elseif (!empty($vars['items'])) {
    $items = $vars['items'];
  }
  else {
    $items = array();
  }

  foreach ($items as $key => $item) {
    if (!empty($item['content']) && !empty($item['content']['#paragraph'])) {
      $entity = $item['content']['#paragraph'];

      try {
        $row = array();

        foreach ($field_array as $field_name) {
          if ($entity->hasField($field_name)) {
            $field = $entity->get($field_name);
            $field_type = $field->getFieldDefinition()->getType();

            switch ($field_type) {
              case 'image':
                foreach ($field as $key => $item) {
                  if (!empty($item->entity)) {
                    $img_url = $item->entity->url();
                    $row[$field_name][$key]['value'] = $img_url;
                    $row[$field_name][$key]['uri'] = $item->entity->getFileUri();
                  }
                }
                break;
              default:
                $row[$field_name] = $field->getValue();
            }
          }
        }
        $rows[] = $row;
      } catch (Exception $exc) {
        \Drupal::logger('error')
          ->error('See ' . __FUNCTION__ . '() <pre>' . $exc->getTraceAsString() . '</pre>');
      }
    }
  }

  return $rows;
}

/**
 * Get block.
 */
function _senate_get_block($bid) {
  $render = '';
  $block = \Drupal\block\Entity\Block::load($bid);

  if (!empty($block)) {
    $render = \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($block);
  }

  return $render;
}

function senate_preprocess(&$vars, $hook) {
  $vars['theme_path'] = base_path() . drupal_get_path('theme', 'senate');
}

/**
 * Return the rendered view with contextual filter.
 * @param string $view_id - The view machine name.
 * @param string $display_id - The display machine name.
 * @param array $arguments - The arguments to pass.
 *
 * @return object $result
 */
function _senate_get_view($view_id, $display_id, array $arguments = []) {
  $result = false;
  $view = Views::getView($view_id);

  if (is_object($view)) {
    $view->setDisplay($display_id);
    $view->setArguments($arguments);
    $view->execute();
    $total_rows = count($view->result);
    $view_res = $view->render();

    $result = \Drupal::service('renderer')->render($view_res);
  }

  return !empty($total_rows) ? $result : '';
}

/**
 * Implements template_theme_suggestions_node_HOOK_alter().
 * Add theme suggestions to the view exposed forms.
 */
function senate_theme_suggestions_views_exposed_form_alter(&$suggestions, $vars, $hook) {
  global $base_path;
  $vars['theme_path'] = $base_path . \Drupal::theme()
      ->getActiveTheme()
      ->getPath();

}

function senate_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  global $base_path;
  $theme_path = $base_path . \Drupal::theme()
      ->getActiveTheme()
      ->getPath();

  if (!empty($form['zip'])){
    $form['zip']['#prefix'] = "<div class=\"sSen__filIco\">
            <img src=\"$theme_path/dist/images/filterIco/senator-filter-icons-1.png\" srcset=\"$theme_path/dist/images/filterIco/senator-filter-icons-1-2x.png 2x\"  alt=\"\">
        </div><div class=\"sSen__opt form f-search f-search_min\">";
    $form['zip']['#suffix'] = "</div>";
    $form['zip']['#attributes']['data-bef-auto-submit-exclude'] = '1';
    $form['zip']['#attributes']['autocomplete'] = 'new-password';
  }

  if (!empty($form['county'])){
    $form['county']['#prefix'] = " <div class=\"sSen__filCol\">
        <div class=\"sSen__filIco\">
            <img src=\"$theme_path/dist/images/filterIco/senator-filter-icons-2.png\" srcset=\"$theme_path/dist/images/filterIco/senator-filter-icons-2-2x.png 2x\"  alt=\"\">
        </div>";
    $form['county']['#suffix'] = "</div>";
  }

  if (!empty($form['district'])){
    $form['district']['#prefix'] = " <div class=\"sSen__filCol\">
        <div class=\"sSen__filIco\">
            <img src=\"$theme_path/dist/images/filterIco/senator-filter-icons-3.png\" srcset=\"$theme_path/dist/images/filterIco/senator-filter-icons-3-2x.png 2x\"  alt=\"\">
        </div>";
    $form['district']['#suffix'] = "<div class=\"sSen__filLink\">
            <a href=\"/OKSenateDistrictMap\" target=\"_blank\">see district map</a>
        </div></div>";
  }

  if (!empty($form['committee'])){
    $form['committee']['#prefix'] = " <div class=\"sSen__filCol\">
        <div class=\"sSen__filIco\">
            <img src=\"$theme_path/dist/images/filterIco/senator-filter-icons-4.png\" srcset=\"$theme_path/dist/images/filterIco/senator-filter-icons-4-2x.png 2x\"  alt=\"\">
        </div>";
    $form['committee']['#suffix'] = "</div>";
  }

  if (!empty($form['party'])){
    $form['party']['#prefix'] = " <div class=\"sSen__filCol\">
        <div class=\"sSen__filIco\">
            <img src=\"$theme_path/dist/images/filterIco/senator-filter-icons-5.png\" srcset=\"$theme_path/dist/images/filterIco/senator-filter-icons-5-2x.png 2x\"  alt=\"\">
        </div>";
    $form['party']['#suffix'] = "</div>";
  }

}

/**
 * Implements hook_preprocess_views_view_list();
 */
function senate_preprocess_views_view_list(&$vars) {
  $view = $vars['view'];
  $id = $view->id();
  $display_id = $view->current_display;

  switch ($id) {
    case 'committee_dropdown':
      $args = !empty($view->args) ? $view->args[0] : '';
      $vars['empty_title'] = t('Select Committee');
      if (!empty($args)) {
        $args = explode(',', $args);
        $ancestors = \Drupal::service('entity_type.manager')
          ->getStorage("taxonomy_term")->loadParents($args[0]);
        if (!empty($ancestors)) {
          $vars['empty_title'] = t('Select Subcommittee');
        }
      }
      break;
  }
}

/**
 * Implements hook_preprocess_views_view_unformatted();
 */
function senate_preprocess_views_view_unformatted(&$vars) {
  $view = $vars['view'];
  $id = $view->id();
  $display_id = $view->current_display;

  switch ($id) {
    case 'subcommittee_agencies':
      $rows = !empty($vars["rows"]) ? $vars["rows"] : [];
      $vars['unique_items'] = [];
      $vars['agency_doc_path'] = SENATE_AGENCIES_DOC_BASE_PATH;
      $current_path = \Drupal::service('path.current')->getPath();
      $path_args = explode('/', $current_path);
      $arg_0 = !empty($path_args[1]) ? $path_args[1] : '';
      $arg_1 = !empty($path_args[2]) ? $path_args[2] : '';
      if (($arg_0 == 'node') && is_numeric($arg_1)) {
        $alias = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
        $alias_args = explode('/', $alias);
        $last = array_pop($alias_args);
        if (!empty($last)) {
          $vars['agency_doc_path'] = str_replace('/education/', '/' . $last . '/', $vars['agency_doc_path']);
        }
      }

      foreach ($rows as $key => $row) {
        $tid = (!empty($row["content"]) && !empty($row["content"]["#row"])) ?
          $row["content"]["#row"]->tid : '';
        if (!in_array($tid, $vars['unique_items'])) {
          $vars['unique_items'][$key] = $tid;
        }
      }
      break;
    case 'journals':
      $row = !empty($vars["rows"]) ? current($vars["rows"]) : '';
      $nid = (!empty($row) && !empty($row["content"]) &&
        !empty($row["content"]["#row"]->field_journals_files_paragraphs_item_field_data_nid)) ?
        $row["content"]["#row"]->field_journals_files_paragraphs_item_field_data_nid : '';
      if (!empty($nid)) {
        $parent_node = \Drupal\node\Entity\Node::load($nid);

        if ($parent_node->hasField('title')) {
          $title = $parent_node->get('title');
          $title = $title->getValue();
          $vars["title"] = !empty($title) && !empty($title[0]) ? $title[0]['value'] : '';
        }
        if ($parent_node->hasField('field_journals_subtitle')) {
          $subtitle = $parent_node->get('field_journals_subtitle');
          $subtitle = $subtitle->getValue();
          $vars["subtitle"] = !empty($subtitle) && !empty($subtitle[0]) ? $subtitle[0]['value'] : '';
        }
      }
      break;
    case 'senate_staff':
      $rows = !empty($vars["rows"]) ? $vars["rows"] : [];
      $letters = [];
      foreach ($rows as $key => $row) {
        $paragraph = !empty($row["content"]) ? $row["content"]["#paragraph"] : '';
        $name = !empty($paragraph) && $paragraph->hasField('field_staff_name') ?
          $paragraph->get('field_staff_name') : '';
        $name = !empty($name) ? $name->get(0)->value : '';
        $name_arr = explode(' ', $name);
        $name = end($name_arr);

        $letter = substr($name, 0, 1);
        $letter = strtolower($letter);
        $letters[$key] = $letter;
      }
      $vars['letters'] = $letters;
      break;

    case 'issue_papers':
      $row = !empty($vars["rows"]) ? current($vars["rows"]) : '';
      $nid = (!empty($row) && !empty($row["content"]) &&
        !empty($row["content"]["#row"]->nid)) ?
        $row["content"]["#row"]->nid : '';
      if (!empty($nid)) {
        $node = \Drupal\node\Entity\Node::load($nid);
        if ($node->hasField('field_issue_page_type')) {
          $type = $node->get('field_issue_page_type');
          $type = $type->getValue();
          if (!empty($type)) {

          $term_obj = Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->load($type[0]['target_id']);

            $term_type = $term_obj->getName();
            $vars['wrapper'] = [''];
            switch ($term_type) {
              case "Text":
                $vars['wrapper'][] = 'bTiles bTiles_rel bTiles_rel_b bTiles_gap_a';
                $vars['inner_wrapper'] = new Attribute(['class' => ['bTiles__items']]);
                break;
              case "Links":
              case "Files":
                $vars['wrapper'][] = 'bListItems bListItems_a bListItems_gap_a';
                $vars['inner_wrapper'] = new Attribute(['class' => ['bListItems__items']]);
                break;
            }
          }
        }
      }
      break;
    case 'senators':
      if ($view->current_display == 'block_1'){
        $unique_items = [];
        $rows = !empty($vars["rows"]) ? $vars["rows"] : [];
        foreach ($rows as $key => $row) {
          if (in_array($row['content']['#row']->nid, $unique_items)) {
            unset($vars["rows"][$key]);
          }
          $unique_items[] = $row['content']['#row']->nid;
        }
      }
      break;
  }
}
function senate_preprocess_views_view_fields(&$vars) {

  $fields = $vars['fields'];
  if ($vars['view']->id() == 'senators'){

    $view_obj = $vars['view'];
    $exposed_inp = $view_obj->getExposedInput();
    $exposd_inp_committee = !empty($exposed_inp["committee"]) ? $exposed_inp["committee"] : '';
    $committee_filter_value = Term::load($exposd_inp_committee);

    if (!empty($exposd_inp_committee)) {
      $expsed_committee_chair = '';
      $expsed_committee_vicechair = '';

      if (!empty($committee_filter_value) && is_object($committee_filter_value)) {
        if (isset($committee_filter_value->get('field_committee_chair')->entity)) {
          $committee_chair_value = $committee_filter_value->get('field_committee_chair')
            ->getValue();
          $expsed_committee_chair = reset($committee_chair_value);
        }
        if (isset($committee_filter_value->get('field_committee_vice_chairman')->entity)) {
          $committee_vice_chairman_value = $committee_filter_value->get('field_committee_vice_chairman')
            ->getValue();
          $expsed_committee_vicechair = reset($committee_vice_chairman_value);
        }
      }

      if (!empty($expsed_committee_chair) && !empty($fields['nid']) &&
        ($expsed_committee_chair['target_id'] == $fields['nid']->content)) {
        $vars['post'] = t('Chair');

      }
      if (!empty($expsed_committee_vicechair) && !empty($fields['nid']) &&
        $expsed_committee_vicechair['target_id'] ==  $fields['nid']->content) {
        $vars['post'] = t('Vice Chair');
      }
    }

  }


  if (!empty($fields['field_issue_page_type'])) {

    $type = $fields['field_issue_page_type']->content;
    switch ($type){
      case "Text":
        $vars['type'] = 'text';
        break;
      case "Links":
        $vars['type'] = 'link';
      break;
      case "Files":
      $vars['type'] = 'files';
      break;
    }
  }
}
/**
 * Implements hook_preprocess_views_view();
 */
function senate_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  $id = $view->id();
  $display_id = $view->current_display;

  $vars['socials'] = _senate_get_socials($view, 'view');

  switch ($id) {
    case 'senators':
      $vars['total_rows'] = Markup::create("<h4>Showing " . $view->total_rows ." Senators</h4>");
      $exp_input = $view->getExposedInput();
      $zip_exp_input = !empty($exp_input["zip"]) ? $exp_input["zip"] : '';
      $vars['show_search_address_txt'] = !empty($zip_exp_input) && ($view->total_rows > 1) ? TRUE : FALSE;
      break;
    case 'subcommittee_events':
      $tid = !empty($view->args) ? $view->args[0] : '';
      if (!empty($tid)) {
        $tid = explode(',', $tid);
        $parent = Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadAllParents($tid[0]);
        $term_obj = reset($parent);
        if (!empty($term_obj)) {
          $vars['committee_name'] = Markup::create("<h2>Upcoming " . $term_obj->getName() ." Events</h2>");
          $vars['events_url'] = "/upcoming-events/" . $view->args[0];
        }
      }
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      $vars['webform'] = _senate_get_block('webform_notification_block');
      break;
    case 'agencies_documents':
      $tid = !empty($view->args) ? $view->args[1] : '';
      if (!empty($tid) && is_numeric($tid)) {
        $term_obj = Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($tid);
        $vars['title'] = $term_obj->getName();
      }
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      break;
    case 'session_summary':
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      $archive = _senate_get_session_summary_years();
      $vars['select_year'] = [
        '#theme' => 'senate_session_summary_select',
        '#archive' => $archive,
      ];
      break;
    case 'issue_papers':
      $archive = _senate_get_issue_type_terms();
      $vars['select_issue'] = [
        '#theme' => 'senate_issue_type_select',
        '#archive' => $archive,
      ];

      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      break;

    case 'week_review':
      $archive = _senate_get_archive_week_review();
      $current_path = \Drupal::service('path.current')->getPath();

      $vars['sidebar'] = [
        '#theme' => 'senate_news_sidebar',
        '#archive' => $archive,
        '#current_path' => $current_path,
      ];
      $date = $view->args;
      if (!empty($date) && !empty($date[0])) {
        $date_obj = new DrupalDateTime($date[0]);
        $vars['showing'] = $date_obj->format('F, Y');
      }
      else {
        $vars['showing'] = t('All');
      }
      break;
    case 'press_releases_audio':
    case 'press_releases':
      $is_audio = ($id === 'press_releases_audio');
      $archive = _senate_get_archive_press_releases_review($is_audio);
      $current_path = \Drupal::service('path.current')->getPath();

      $vars['sidebar'] = [
        '#theme' => 'senate_press_release_sidebar',
        '#archive' => $archive,
        '#current_path' => $current_path,
        '#is_audio' => $is_audio
      ];
      $date = $view->args;
      if (!empty($date) && !empty($date[0])) {
        $date_obj = new DrupalDateTime($date[0]);
        $vars['showing'] = $date_obj->format('F, Y');
      }
      else {
        $vars['showing'] = t('All');
      }
      break;
    case 'journals':
    case 'senate_staff':
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      break;
    case 'calendar_lt_st_journals':
    case 'calendar_lt_joint_app_bd':
      $vars['path_to_theme'] = base_path() . drupal_get_path('theme', 'senate');
      break;
    case 'terms_glossary':
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      $vars['top_text'] = _senate_get_block('glossarydescription');
      $vars['path_to_theme'] = base_path() . drupal_get_path('theme', 'senate');
      break;
    case 'senate_artwork':
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      $vars['path_to_theme'] = base_path() . drupal_get_path('theme', 'senate');

      $exp_input = $view->getExposedInput();
      $location = !empty($exp_input["location"]) ? $exp_input["location"] : '';
      if (!empty($location)) {
        $result = !empty($view->result[0]) ? $view->result[0] : '';
        $entity = !empty($result->_entity) ? $result->_entity : '';

        if (!empty($entity)) {
          $caption = $entity->get('field_edu_indiv_art_work_cap')->getValue();
          $caption = !empty($caption[0]) ? $caption[0]["value"] : '';
          $caption_array = preg_split('/<br[^>]*>/i', $caption);
          $caption_array = !empty($caption_array) ? $caption_array : [];
          foreach ($caption_array as $value) {
            if (strpos($value, 'Location') !== FALSE) {
              $value = html_entity_decode($value);
              $value = strip_tags($value);
              $value = str_replace('Location:', '', $value);
              $location = trim($value);
            }
          }
        }

        $vars['top_text'] = $location;
      }
      else {
        $vars['top_text'] = _senate_get_block('senateartworkdescription');
      }
      break;
    case 'senate_votes':
    case 'committees':
      $vars['path_to_theme'] = base_path() . drupal_get_path('theme', 'senate');
      break;
    case 'search_statutes_constitutions':
      $exposed_input = $view->getExposedInput();
      if (!empty($exposed_input)) {
        $query = !empty($exposed_input["constitutions"]) && !empty($exposed_input["op"]) &&
          ($exposed_input["op"] == 'constitutions_submit') ? $exposed_input["constitutions"] : '';
        $vars['query_text'] = empty($query) && !empty($exposed_input["statutes"]) ?
          $exposed_input["statutes"] : $query;
      }
      break;
    case 'senator_press_release':
      $args = !empty($view->args) ? $view->args : [];
      $senator_name = !empty($args[0]) ? $args[0] : '';
      $nid = $senator_name;
      $date = !empty($args[1]) ? $args[1] : '';
      if (!empty($senator_name) && !is_numeric($senator_name)) {
        $nid = CustomNidToAuthor::convertSenatorNameToNid($senator_name);
      }

      if (!empty($nid) && is_numeric($nid)) {
        $node_storage = \Drupal::entityTypeManager()->getStorage('node');
        $node = $node_storage->load($nid);
        $name = !empty($node) ? $node->get('title')->value : '';
        $vars['title'] = t("Sen. @name’s Press Releases", [
          '@name' => $name,
        ]);

        $archive = _senate_get_archive_press_releases_review(FALSE, $nid);
        $current_path = \Drupal::service('path.current')->getPath();

        $vars['sidebar'] = [
          '#theme' => 'senate_press_release_sidebar',
          '#archive' => $archive,
          '#current_path' => $current_path,
          '#is_audio' => FALSE,
          '#senator_nid' => $senator_name,
        ];
      }

      if (!empty($date)) {
        $date_obj = new DrupalDateTime($date);
        $vars['showing'] = $date_obj->format('F, Y');
      }
      else {
        $vars['showing'] = t('All');
      }
      $vars['breadcrumbs'] = _senate_get_block('custombreadcrumbblock');
      break;
    case 'senator_recent_news':
      $vars['news_url'] = SENATE_SENATOR_RECENT_NEWS_URL . "/" . $view->args[0];
      break;
    case 'senator_rec_news_land':
      $args = !empty($view->args) ? $view->args : [];
      $senator_id = !empty($args[0]) ? $args[0] : '';
      $archive = _senate_get_archive_senator_blog_post($senator_id);
      $current_path = \Drupal::service('path.current')->getPath();

      $vars['sidebar'] = [
        '#theme' => 'senator_blog_post_sidebar',
        '#archive' => $archive,
        '#current_path' => $current_path,
        '#base_path' => SENATE_SENATOR_RECENT_NEWS_URL . "/" . $senator_id,
      ];
      $date = !empty($args[1]) ? $args[1] : '';
      if (!empty($date)) {
        $date_obj = new DrupalDateTime($date);
        $vars['showing'] = $date_obj->format('F, Y');
      }
      else {
        $vars['showing'] = t('All');
      }
      break;
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function senate_preprocess_paragraph(array &$vars) {
  $paragraph = $vars['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'publications':
      $node = \Drupal::routeMatch()->getParameter('node');
      if (!empty($node) && is_object($node) && $node->id() == SENATE_CONTACTS_LANDING_NID) {
        $vars['icon_attributes'] = ' bTiles__ico_a';
      }

      $link = !empty($vars["content"]["field_par_publications_page_link"]) &&
        !empty($vars["content"]["field_par_publications_page_link"]["#items"]) ?
        $vars["content"]["field_par_publications_page_link"]["#items"]->getValue() : '';
      $link_att = !empty($link) && !empty($link[0]["options"]) ? $link[0]["options"]["attributes"] : [];
      $link_att['class'] = ['bTiles__item'];
      $vars['link_attr'] = new Attribute($link_att);
      break;
    case 'journals_files':
      $date = (!empty($vars["content"]["field_journals_files_date"]) &&
        !empty($vars["content"]["field_journals_files_date"]['#items'])) ?
        $vars["content"]["field_journals_files_date"]['#items']->getValue() : '';
      $file = (!empty($vars["content"]["field_journals_files_file"]) &&
        !empty($vars["content"]["field_journals_files_file"][0])) ?
        $vars["content"]["field_journals_files_file"][0]['#file'] : '';

      $date = !empty($date) && !empty($date[0]) ? $date[0]["value"] : '';
      $vars['file_url'] = !empty($file) ? file_create_url($file->getFileUri()) : '';
      $date_obj = new DrupalDateTime($date);
      $vars['date'] = $date_obj->format('F j');

      if ($vars["view_mode"] == 'calendar_landing') {
        $vars['date'] = $date_obj->format('F j, Y');
      }
      break;
    case 'staff':
      $email = (!empty($vars["content"]["field_staff_email"]) &&
        !empty($vars["content"]["field_staff_email"]['#items'])) ?
        $vars["content"]["field_staff_email"]['#items']->getValue() : '';
      $vars['email'] = !empty($email) && !empty($email[0]) ? $email[0]["value"] : '';
      break;
    case 'video':
    case 'gallery_video':
      if (!empty($vars['content']['field_video_video']) &&
        !empty($vars['content']['field_video_video']['#items'])) {
        $items = $vars['content']['field_video_video']['#items'];
        $value = !empty($items) ? $items->getValue() : '';
        if (!empty($value)) {
          $url = $value[0]['value'];
          $video_data = _get_youtube_embed_data($url, ['rel' => 0, 'controls' => 0, 'showinfo' => 0, 'enablejsapi' => 1]);
          $vars['video_id'] = !empty($video_data['video_id']) ? $video_data['video_id'] : '';
          $vars['video_url'] = !empty($video_data['url']) ? $video_data['url'] : '';
        }
      }
      break;
    case 'gallery_image':
      if (!empty($vars['content']['field_gallery_par_image'][0]['#item'])){
        $gallery_img_uri = $vars['content']['field_gallery_par_image'][0]['#item']->entity->url();
      }
      $vars['gallery_img_uri'] = !empty($gallery_img_uri) ? $gallery_img_uri : '';
      $vars['gallery_img_download_target'] = !empty($vars['gallery_img_uri']) ? end(explode('/',$vars['gallery_img_uri'])) : '';

      break;
    case 'senate_votes':
      $measure = (!empty($vars["content"]["field_senate_votes_measure"]) &&
        !empty($vars["content"]["field_senate_votes_measure"]['#items'])) ?
        $vars["content"]["field_senate_votes_measure"]['#items']->getValue() : '';
      $measure_link = (!empty($vars["content"]["field_senate_votes_measure_link"]) &&
        !empty($vars["content"]["field_senate_votes_measure_link"]['#items'])) ?
        $vars["content"]["field_senate_votes_measure_link"]['#items']->getValue() : '';

      $author = (!empty($vars["content"]["field_senate_votes_author"]) &&
        !empty($vars["content"]["field_senate_votes_author"]['#items'])) ?
        $vars["content"]["field_senate_votes_author"]['#items']->getValue() : '';
      $author_link = (!empty($vars["content"]["field_senate_votes_author_link"]) &&
        !empty($vars["content"]["field_senate_votes_author_link"]['#items'])) ?
        $vars["content"]["field_senate_votes_author_link"]['#items']->getValue() : '';

      $vars["measure"] = !empty($measure) && !empty($measure[0]) ? $measure[0]["value"] : '';
      $measure_link = !empty($measure_link) && !empty($measure_link[0]) ? $measure_link[0]["uri"] : '';

      $vars["author"] = !empty($author) && !empty($author[0]) ? $author[0]["value"] : '';
      $author_link = !empty($author_link) && !empty($author_link[0]) ? $author_link[0]["uri"] : '';

      if (!empty($vars["measure"]) && !empty($measure_link)) {
        $url = Url::fromUri($measure_link);

        $attributes['target'] = '_blank';
        $url->setOption('attributes', $attributes);
        $vars["measure"] = Link::fromTextAndUrl($vars["measure"], $url);
      }

      if (!empty($vars["author"]) && !empty($author_link)) {
        $url = Url::fromUri($author_link);
        $vars["author"] = Link::fromTextAndUrl($vars["author"], $url);
      }
      break;
  }
}

/**
 * Years of existing nodes.
 * @param $tid
 *
 * @return array
 */
function _senate_get_years_existing_nodes($tid) {
  if (empty($tid)) {
    return [];
  }

  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'agencies_doc')
    ->condition('nfd.status', 1);
  $query->innerJoin('node__field_agencies_doc_agency', 'ag', 'ag.entity_id = nfd.nid and ag.deleted = 0');
  $query->innerJoin('node__field_agencies_doc_year', 'year', 'year.entity_id = nfd.nid and year.deleted = 0');
  $query->fields('year', ['field_agencies_doc_year_value'])
    ->condition('ag.field_agencies_doc_agency_target_id', $tid);
  $query->distinct(TRUE);
  $result = $query->execute()->fetchCol();

  return !empty($result) ? $result : [];
}


function _get_youtube_embed_data($url, $query_options = array()) {
  $vars = [];
  parse_str(parse_url($url, PHP_URL_QUERY), $parts);

  if (isset($parts['v'])) {
    $vars['video_id'] = Html::escape($parts['v']);
    $embed_path = '/embed/' . $vars['video_id'];
  }
  elseif (isset($parts['l'])) {
    $vars['video_id'] = Html::escape($parts['l']);
    $embed_path = '/embed/videoseries';
  }
  if (!empty($embed_path)) {
    $url = Url::fromUri('https://www.youtube.com'  . $embed_path, ['query' => $query_options, 'external' => TRUE]);
    $vars['url'] = $url->toString();
  }

  return $vars;
}

function _senate_get_committee_options($committee_options) {
  if (!empty($committee_options["All"])) {
    $new_options['All'] = t('Select Committee');
  }

  $new_options['Standing Committees'] = [];
  $new_options['Subcommittees'] = [];

  $tree = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
    ->loadTree('committees', 0, NULL, FALSE);
  $first_level_tids = [];
  $second_level_tids = [];
  foreach ($tree as $term) {
    $parent = (!empty($term->parents) && isset($term->parents[0])) ? $term->parents[0] : '';
    if ($parent === '0') {
      $first_level_tids[] = $term->tid;
    }
    else {
      $second_level_tids[] = $term->tid;
    }
  }

  foreach ($committee_options as $tid => $name) {
    if (in_array($tid, $first_level_tids)) {
      $new_options['Standing Committees'][$tid] = $name;
    }
    elseif (in_array($tid, $second_level_tids)) {
      $new_options['Subcommittees'][$tid] = $name;
    }
  }

  return $new_options;
}

/**
 * Implements hook_theme().
 */
function senate_theme($existing, $type, $theme, $path) {
  $theme_path = base_path() . drupal_get_path('theme', 'senate');
  return [
    'senate_news_sidebar' => [
      'variables' => [
        'archive' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_press_release_sidebar' => [
      'variables' => [
        'archive' => NULL,
        'current_path' => NULL,
        'is_audio' => false,
        'senator_nid' => false,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_session_summary_select' => [
      'variables' => [
        'archive' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_issue_type_select' => [
      'variables' => [
        'archive' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_news_sharethis' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_socials' => [
      'variables' => [
        'entity' => NULL,
        'entity_type' => NULL,
        'url' => NULL,
        'title' => NULL,
        'printer' => NULL,
        'color' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_subscribe_form' => [
      'variables' => [
        'type' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senate_video_popup' => [
      'variables' => [
        'type' => NULL,
        'current_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
    'senator_blog_post_sidebar' => [
      'variables' => [
        'archive' => NULL,
        'current_path' => NULL,
        'base_path' => NULL,
      ],
      'path' => $theme_path . '/templates/theme',
    ],
  ];
}

function _senate_get_archive_week_review() {
  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'week_review')
    ->condition('nfd.status', 1);
  $query->innerJoin('node__field_week_review_date', 'rd', 'rd.entity_id = nfd.nid AND rd.deleted = 0 AND rd.bundle = \'week_review\'');

  $query->addExpression("DATE_FORMAT(field_week_review_date_value, '%M')", 'month');
  $query->addExpression("DATE_FORMAT(field_week_review_date_value, '%m')", 'month_digits');
  $query->addExpression("DATE_FORMAT(field_week_review_date_value, '%Y')", 'year');

  $query->groupBy('year');
  $query->groupBy('month_digits');
  $query->groupBy('month');
  $query->orderBy('year', 'desc');
  $query->orderBy('month_digits', 'desc');

  $result = $query->execute()->fetchAll();

  $archive = [];
  foreach ($result as $row) {
    $archive[$row->year][$row->month] = $row;
  }

  return !empty($archive) ? $archive : [];
}

function _senate_get_archive_press_releases_review($only_with_audio = FALSE, $senator_nid = FALSE) {
  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'press_release')
    ->condition('nfd.status', 1);
  $query->innerJoin('node__field_date', 'rd', 'rd.entity_id = nfd.nid AND rd.deleted = 0 AND rd.bundle = \'press_release\'');

  $query->addExpression("DATE_FORMAT(field_date_value, '%M')", 'month');
  $query->addExpression("DATE_FORMAT(field_date_value, '%m')", 'month_digits');
  $query->addExpression("DATE_FORMAT(field_date_value, '%Y')", 'year');

  if($only_with_audio) {
    $query->innerJoin('node__field_press_release_audio', 'audio', 'nfd.nid= audio.entity_id');
  } else {
    $query->leftJoin('node_revision__field_press_release_type', 'pst', 'nfd.nid=pst.entity_id');
    $query->isNull('pst.field_press_release_type_value');
  }
  if (!empty($senator_nid)) {
    $query->innerJoin('node__field_senator', 'senator', 'nfd.nid = senator.entity_id AND senator.field_senator_target_id = ' . $senator_nid);
  }

  $query->groupBy('year');
  $query->groupBy('month_digits');
  $query->groupBy('month');
  $query->orderBy('year', 'desc');
  $query->orderBy('month_digits', 'desc');

  $result = $query->execute()->fetchAll();
//  $a = $query->__toString();

  $archive = [];
  foreach ($result as $row) {
    $archive[$row->year][$row->month] = $row;
  }

  return !empty($archive) ? $archive : [];
}

function _senate_get_session_summary_years() {
  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'session_summary')
    ->condition('nfd.status', 1);
  $query->innerJoin('node__field_session_summary_year_date', 'rd', 'rd.entity_id = nfd.nid AND rd.deleted = 0 AND rd.bundle = \'session_summary\'');
  $query->addExpression("DATE_FORMAT(field_session_summary_year_date_value, '%Y')", 'year');
  $query->orderBy('year', 'desc');
  $result = $query->execute()->fetchAll();

  $archive = [];
  $archive[0] = 'Select a year';
  foreach ($result as $row) {
    $archive[] = $row->year;
  }

  return !empty($archive) ? $archive : [];
}

function _senate_get_journals_options() {
  $query = \Drupal::database()->select('paragraphs_item_field_data', 'pifd')
    ->condition('pifd.type', 'journals_files')
    ->condition('pifd.status', 1);
  $query->innerJoin('node__field_journals_files', 'nfjf', 'pifd.id = nfjf.field_journals_files_target_id AND nfjf.deleted = 0');
  $query->innerJoin('node_field_data', 'nfd', 'nfjf.entity_id = nfd.nid AND nfd.status = 1 AND nfd.type = \'journals\'');
  $query->innerJoin('paragraph__field_journals_files_date', 'pfjfd', 'pifd.id = pfjfd.entity_id AND pfjfd.deleted = 0');

  $query->addExpression("DATE_FORMAT(field_journals_files_date_value, '%M')", 'month');
  $query->addExpression("DATE_FORMAT(field_journals_files_date_value, '%m')", 'month_digits');
  $query->addExpression("DATE_FORMAT(field_journals_files_date_value, '%Y')", 'year');
  $query->addExpression("DATE_FORMAT(field_journals_files_date_value, '%d')", 'day');

  $query->groupBy('year');
  $query->groupBy('month_digits');
  $query->groupBy('month');
  $query->groupBy('day');
  $query->orderBy('year', 'desc');
  $query->orderBy('month_digits', 'asc');
  $query->orderBy('day', 'asc');

  $result = $query->execute()->fetchAll();

  $options = [];
  foreach ($result as $row) {
//    $options[$row->year][$row->month_digits] = $row->month;
    $options['options'][$row->year][$row->month_digits]['month'] = $row->month;
    $options['options'][$row->year][$row->month_digits]['days'][$row->day] = (int)$row->day;
    $options['dates'][] = $row->month_digits . "/" . $row->day . "/" . $row->year;
  }

  return !empty($options) ? $options : [];
}

function _senate_votes_get_grouped_items($pr_ids) {
  $query = \Drupal::database()->select('paragraph__field_senate_votes_measure', 'pfsvm')
    ->fields('pfsvm', ['entity_id', 'field_senate_votes_measure_value'])
    ->condition('pfsvm.bundle', 'senate_votes')
    ->condition('pfsvm.deleted', 0)
    ->condition('pfsvm.entity_id', $pr_ids, 'IN')
    ->orderBy('field_senate_votes_measure_value', 'ASC');
  $result = $query->execute()->fetchAll();

  $grouped = [];
  foreach ($result as $row) {
    $grouped[$row->field_senate_votes_measure_value][] = $row->entity_id;
  }

  return !empty($grouped) ? $grouped : [];
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function senate_preprocess_views_view_field(&$vars) {
  $view = $vars['view'];
  $id = $view->id();
  $display_id = $view->current_display;

  switch ($id) {
    case 'search_statutes_constitutions':
      $items = $vars['field']->getItems($vars["row"]);
      if (!empty($items) && !empty($items[0])) {
        $options = ['class' => ['bListLinks__link']];
        $options['target'] = '_blank';
        $items[0]["rendered"]["#url"]->setOption('attributes', $options);

        $parent_node = !empty($vars["row"]->_relationship_entities) &&
          !empty($vars["row"]->_relationship_entities["reverse_field_statutes_constit_files_node"]) ?
          $vars["row"]->_relationship_entities["reverse_field_statutes_constit_files_node"] : '';
        $fid = !empty($vars["row"]->fid) ? $vars["row"]->fid : '';
        $files = !empty($parent_node) ? $parent_node->field_statutes_constit_files->getValue() : [];
        foreach ($files as $file) {
          if (!empty($file["target_id"]) && ($file["target_id"] == $fid)) {
            $file_name = !empty($items[0]["rendered"]["#title"]) ? pathinfo($items[0]["rendered"]["#title"]) : '';
            $file_name = !empty($file_name['filename']) ? $file_name['filename'] : '';
            $file_name = !empty($file["description"]) ? $file["description"] : $file_name;
            $items[0]["rendered"]["#title"] = $file_name;
          }
        }
        $vars["output"] = $items[0]["rendered"];
      }
      break;
    case 'senate_votes_inner':
      $field_name = !empty($vars['field']) ? $vars['field']->field : '';
      $paragraph = !empty($vars["row"]) && !empty($vars["row"]->_entity) ? $vars["row"]->_entity : '';

      if (!empty($paragraph)) {
        if ($field_name == 'field_senate_votes_measure') {
          $measure = $paragraph->hasField('field_senate_votes_measure') ?
            $paragraph->get('field_senate_votes_measure') : '';
          $measure = !empty($measure) && !empty($measure->get(0)) ? $measure->get(0)->value : '';

          $measure_link = $paragraph->hasField('field_senate_votes_measure_link') ?
            $paragraph->get('field_senate_votes_measure_link') : '';
          $measure_link = !empty($measure_link) && !empty($measure_link->get(0)) ?
            $measure_link->get(0)->uri : '';

          if (!empty($measure) && !empty($measure_link)) {
            $url = Url::fromUri($measure_link);

            $attributes['target'] = '_blank';
            $url->setOption('attributes', $attributes);
            $vars["output"] = Link::fromTextAndUrl($measure, $url)->toString();
          }
        }
        else if ($field_name == 'field_senate_votes_author') {
          $author = $paragraph->hasField('field_senate_votes_author') ?
            $paragraph->get('field_senate_votes_author') : '';
          $author = !empty($author) && !empty($author->get(0)) ? $author->get(0)->value : '';

          $author_link = $paragraph->hasField('field_senate_votes_author_link') ?
            $paragraph->get('field_senate_votes_author_link') : '';
          $author_link = !empty($author_link) && !empty($author_link->get(0)) ?
            $author_link->get(0)->uri : '';

          if (!empty($author) && !empty($author_link)) {
            $url = Url::fromUri($author_link);

            $attributes['target'] = '_blank';
            $url->setOption('attributes', $attributes);
            $vars["output"] = Link::fromTextAndUrl($author, $url)->toString();
          }
        }
        else if ($field_name == 'field_senate_votes_action_link') {
          $url = $paragraph->hasField('field_senate_votes_action_link') ?
            $paragraph->get('field_senate_votes_action_link') : '';
          $link = !empty($url) && !empty($url->get(0)) ? $url->get(0)->uri : '';
          $title = !empty($url) && !empty($url->get(0)) ? $url->get(0)->title : '';

          if (!empty($link) && !empty($title)) {
            $url = Url::fromUri($link);

            $attributes['target'] = '_blank';
            $attributes['class'] = ['bTb__text', 'bTb__text_a',];
            $url->setOption('attributes', $attributes);
            $vars["output"] = Link::fromTextAndUrl($title, $url)->toString();
          }
        }
        else if ($field_name == 'field_senate_votes_action_file') {
          $file = $paragraph->hasField('field_senate_votes_action_file') ?
            $paragraph->get('field_senate_votes_action_file') : '';
          $description = !empty($file) && !empty($file->get(0)) ? $file->get(0)->description : '';
          $fid = !empty($file) && !empty($file->get(0)) ? $file->get(0)->target_id : '';
          $file = !empty($fid) ? \Drupal\file\Entity\File::load($fid) : '';

          if (!empty($file)) {
            $url = $file->createFileUrl(FALSE);
            $url = Url::fromUri($url);
            $options = ['class' => ['bTb__text', 'bTb__text_a',]];
            $options['target'] = '_blank';

            $url->setOption('attributes', $options);
            $vars['output'] = Link::fromTextAndUrl($description, $url);
          }
        }
      }
      break;
  }
}

function _senate_get_staff_options() {
  $query = \Drupal::database()->select('paragraphs_item_field_data', 'pifd')
    ->condition('pifd.type', 'staff')
    ->condition('pifd.status', 1);
  $query->innerJoin('node__field_staff', 'nfs', 'pifd.id = nfs.field_staff_target_id AND nfs.deleted = 0');
  $query->innerJoin('node_field_data', 'nfd', 'nfs.entity_id = nfd.nid AND nfd.status = 1 AND nfd.type = \'staff\'');
  $query->innerJoin('paragraph__field_staff_division', 'pfsd', 'pifd.id = pfsd.entity_id AND pfsd.deleted = 0');
  $query->fields('pfsd', ['field_staff_division_value']);

  $query->orderBy('field_staff_division_value', 'asc')->distinct();

  $result = $query->execute()->fetchCol();

  return !empty($result) ? $result : [];
}

/**
 * Used issue type terms
 * @param $tid
 *
 * @return array
 */
function _senate_get_issue_type_terms() {
  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'issue')
    ->condition('nfd.status', 1);
  $query->innerJoin('node__field_issue_type_term', 'rd', 'rd.entity_id = nfd.nid AND rd.deleted = 0 AND rd.bundle = \'issue\'');
  $query->addExpression("field_issue_type_term_target_id", 'term');
  $query->orderBy('field_issue_type_term_target_id', 'asc')->distinct();

  $result = $query->execute()->fetchAll();

  $archive = [];
  $used_tids = [];
  foreach ($result as $key => $row) {
    $term_obj = Drupal::entityTypeManager()
      ->getStorage('taxonomy_term')
      ->load($row->term);
    $term_name = $term_obj->getName();
    if (!in_array($term_name, $used_tids)) {
      $archive[$key]['term_name'] = $term_name;
      $archive[$key]['term_id'] = strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '-', $term_name));;
      $used_tids[] = $term_name;
    }
  }
  array_unshift($archive, ['term_name' => 'Select a paper', 'term_id' => '']);
  return !empty($archive) ? $archive : [];
}

function senate_preprocess_views_view_grouping(&$vars) {
  $view = $vars['view'];
  if ($view->id() == 'issue_papers') {
    $vars['id'] = strtolower(preg_replace('/[^a-zA-Z0-9-]+/', '-', $vars['title']));
  }
}

/**
 * Get socials.
 * @param $entity
 * @param $entity_type
 * @param string $url
 * @param string $title
 * @param string $color
 *
 * @return array
 */
function _senate_get_socials($entity, $entity_type, $url = '', $title = '', $color = '') {
  $sharethis_manager = \Drupal::service('sharethis.manager');
  $st_js = $sharethis_manager->sharethisIncludeJs();

  $socials = [
    '#theme' => 'senate_socials',
    '#entity' => $entity,
    '#entity_type' => $entity_type,
    '#url' => $url,
    '#title' => $title,
    '#printer' => TRUE,
    '#color' => $color,
    '#attached' => [
      'library' => [
        'sharethis/sharethispickerexternalbuttonsws',
        'sharethis/sharethispickerexternalbuttons',
        'sharethis/sharethis',
      ],
      'drupalSettings' => [
        'sharethis' => $st_js,
      ],
    ],
  ];

  return $socials;
}

/**
 * Implements hook_preprocess_HOOK().
 * @param $vars
 */
function senate_preprocess_senate_socials(&$vars) {
  $entity = !empty($vars["entity"]) ? $vars["entity"] : '';
  $entity_type = !empty($vars["entity_type"]) ? $vars["entity_type"] : '';

  $social_class = [
    'fb' => 'ss-facebook st_facebook_custom',
    'tw' => 'ss-twitter st_twitter_custom',
    'email' => 'ss-mail st_email_custom',
  ];

  $color = !empty($color) ? $color : 'white';

  if (!empty($entity) && ($entity_type == 'node')) {
    switch ($entity->bundle()) {
      case 'press_release':
      case 'contact':
      case 'edu_indiv_art_work':
      case 'issue':
      case 'privacy_policy':
      case 'senate_votes':
      case 'senator':
      case 'tables_page':
      case 'week_review':
      case 'protem_podcast':
      case 'senator_blog_post':
      case 'simple_page':
        $color = 'navy';
        break;
    }
  }
  elseif (!empty($entity) && ($entity_type == 'view')) {
    switch ($entity->id()) {
      case 'subcommittee_events':
      case 'agencies_documents':
        $color = 'navy';
        break;
    }
  }

  $vars['socials'] = $social_class;
  $vars['color'] = $color;
  if ($color == 'white') {
    $vars['wrapper_class'] = '';
    $vars['icons_class'] = 'bSoc_cl_a';
  }
  elseif ($color == 'navy') {
    $vars['wrapper_class'] = 'bShare_cl_a';
    $vars['icons_class'] = 'bSoc_cl_b';
  }

  if (empty($vars["url"])) {
    $vars["url"] = Url::fromRoute('<current>', [], ['query' => \Drupal::request()->query->all(), 'absolute' => 'true'])->toString();
  }
  if (empty($vars["title"])) {
    $request = \Drupal::request();
    if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
      $vars["title"] = \Drupal::service('title_resolver')->getTitle($request, $route);
      $vars["title"] = strip_tags($vars["title"]);
    }
  }
  else {
    $vars["title"] = strip_tags($vars["title"]);
  }
}

/**
 * Captcha pre_render.
 */
function senate_change_captcha_description($element) {
  $description = !empty($element["captcha_widgets"]) &&
    !empty($element["captcha_widgets"]["captcha_response"]) &&
    !empty($element["captcha_widgets"]["captcha_response"]["#description"]) ?
    $element["captcha_widgets"]["captcha_response"]["#description"] : '';
  $add_description = t('Math question not to test basic math skills.');
  $title = !empty($element["captcha_widgets"]) && !empty($element["captcha_widgets"]["captcha_response"]) &&
    !empty($element["captcha_widgets"]["captcha_response"]["#title"]) ?
    $element["captcha_widgets"]["captcha_response"]["#title"] : '';
  $add_title = t('CAPTCHA:');

  if (!empty($description)) {
    $desc = is_object($description) ? $description->__toString() : $description;
    $add_desc = $add_description->__toString();

    $has_add_desc = (strpos($desc, $add_desc) !== FALSE);
    if (!$has_add_desc) {
      $element["captcha_widgets"]["captcha_response"]["#description"] = $description . ' ' . $add_description;
    }
  }

  if (!empty($title)) {
    $title = is_object($title) ? $title->__toString() : $title;
    $add_title = $add_title->__toString();

    $has_add_title = (strpos($title, $add_title) !== FALSE);
    if (!$has_add_title) {
      $element["captcha_widgets"]["captcha_response"]["#title"] = $add_title . ' ' . $title;
    }
  }

  return $element;
}

/**
 * Get node created user.
 * @param $uid
 *
 * @return array
 */
function _senate_get_senators_name($uid) {
  if (empty($uid)) {
    return [];
  }

  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->fields('nfd', ['nid', 'title'])
    ->condition('nfd.uid', $uid)
    ->condition('nfd.type', 'senator')
    ->condition('nfd.status', 1);

  $result = $query->execute()->fetchAllKeyed();

  return !empty($result) ? $result : [];
}

function _senate_get_archive_senator_blog_post($uid) {
  if (empty($uid)) {
    return [];
  }

  $query = \Drupal::database()->select('node_field_data', 'nfd')
    ->condition('nfd.type', 'senator_blog_post')
    ->condition('nfd.status', 1)
    ->condition('nfd.uid', $uid);
  $query->innerJoin('node__field_senator_blog_post_posted', 'rd', 'rd.entity_id = nfd.nid AND rd.deleted = 0 AND rd.bundle = \'senator_blog_post\'');

  $query->addExpression("DATE_FORMAT(field_senator_blog_post_posted_value, '%M')", 'month');
  $query->addExpression("DATE_FORMAT(field_senator_blog_post_posted_value, '%m')", 'month_digits');
  $query->addExpression("DATE_FORMAT(field_senator_blog_post_posted_value, '%Y')", 'year');

  $query->groupBy('year');
  $query->groupBy('month_digits');
  $query->groupBy('month');
  $query->orderBy('year', 'desc');
  $query->orderBy('month_digits', 'desc');

  $result = $query->execute()->fetchAll();
  //  $a = $query->__toString();

  $archive = [];
  foreach ($result as $row) {
    $archive[$row->year][$row->month] = $row;
  }

  return !empty($archive) ? $archive : [];
}

/**
 * Implements hook_theme_suggestions_node_alter().
 */
function senate_theme_suggestions_block_alter(array &$suggestions, array $vars) {
  $webform = (!empty($vars["elements"]) && !empty($vars["elements"]["content"]["#webform"])) ?
    $vars["elements"]["content"]["#webform"] : '';

  if (!empty($webform)) {
    $suggestions[] = 'block__webform__' . $webform->id();
  }
}

/**
 * Sign up committee meeting validation.
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function webform_sign_up_committee_meeting_validate($form, FormStateInterface $form_state) {
  $input = $form_state->getUserInput();
  $committees = !empty($input["committees"]) ? $input["committees"] : [];
  if (!empty($committees['all'])) {
    unset($committees['all']);
    $committees_keys = array_keys($committees);
    $form_state->setValue('committees', $committees_keys);
  }
}

function _senate_get_votes_measure_options($nid) {
  if (empty($nid)) {
    return;
  }

  $query = \Drupal::database()->select('paragraphs_item_field_data', 'pifd')
    ->condition('pifd.type', 'senate_votes')
    ->condition('pifd.status', 1);
  $query->innerJoin('node__field_senate_votes', 'nfsv', 'pifd.id = nfsv.field_senate_votes_target_id AND nfsv.deleted = 0');
  $query->innerJoin('node_field_data', 'nfd', 'nfsv.entity_id = nfd.nid AND nfd.status = 1 AND nfd.type = \'senate_votes\'');
  $query->innerJoin('paragraph__field_senate_votes_measure', 'pfsvm', 'pifd.id = pfsvm.entity_id AND pfsvm.deleted = 0');
  $query->fields('pfsvm', ['field_senate_votes_measure_value']);
  $query->condition('nfd.nid', $nid);

  $query->orderBy('field_senate_votes_measure_value', 'asc')->distinct();

  $result = $query->execute()->fetchCol();

  return !empty($result) ? $result : [];
}

function _senate_get_votes_author_options($nid) {
  if (empty($nid)) {
    return;
  }

  $query = \Drupal::database()->select('paragraphs_item_field_data', 'pifd')
    ->condition('pifd.type', 'senate_votes')
    ->condition('pifd.status', 1);
  $query->innerJoin('node__field_senate_votes', 'nfsv', 'pifd.id = nfsv.field_senate_votes_target_id AND nfsv.deleted = 0');
  $query->innerJoin('node_field_data', 'nfd', 'nfsv.entity_id = nfd.nid AND nfd.status = 1 AND nfd.type = \'senate_votes\'');
  $query->innerJoin('paragraph__field_senate_votes_author', 'pfsva', 'pifd.id = pfsva.entity_id AND pfsva.deleted = 0');
  $query->fields('pfsva', ['field_senate_votes_author_value']);
  $query->condition('nfd.nid', $nid);

  $query->orderBy('field_senate_votes_author_value', 'asc')->distinct();

  $result = $query->execute()->fetchCol();

  return !empty($result) ? $result : [];
}

function _senate_get_journals_month_options($year) {
  $month_option = [];
  $year = !empty($year) && is_array($year) ? $year : [];

  foreach ($year as $key => $value) {
    if (!empty($value['month'])) {
      $month_option[$key] = $value['month'];
    }
  }

  return $month_option;
}
