<?php
/**
 * @file
 * Senate redirect custom functionality.
 */

use Drupal\redirect\Entity\Redirect;

/**
 * Batch operation.
 */
function senate_redirect_batch_op(array $items, &$context) {
  $redirect_service = \Drupal::service('redirect.repository');
  $limit = 50;

  if (empty($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['max'] = count($items);
  }

  if (empty($context['sandbox']['items'])) {
    $context['sandbox']['items'] = $items;
  }

  $counter = 0;
  if (!empty($context['sandbox']['items'])) {
    if ($context['sandbox']['progress'] != 0) {
      array_splice($context['sandbox']['items'], 0, $limit);
    }

    foreach ($context['sandbox']['items'] as $url) {
      if ($counter != $limit) {
        if (!empty($url)) {
          $url_short = str_replace('http://www.oksenate.gov/', '', $url);
          $url_short = urldecode($url_short);

          if (!$redirect_service->findMatchingRedirect($url_short, [], 'und')) {
            $nid = array_search($url, $items);
            if (!empty($nid)) {
              $redirect = Redirect::create();
              $redirect->setSource($url_short);
              $redirect->setRedirect('/node/' . $nid);
              $redirect->setLanguage('und');
              $redirect->setStatusCode(301);
              $redirect->save();
            }
          }
        }

        $counter++;
        $context['sandbox']['progress']++;

        $context['message'] = t('Now processing node :progress of :count', [
          ':progress' => $context['sandbox']['progress'],
          ':count' => $context['sandbox']['max'],
        ]);

        $context['results']['processed'] = $context['sandbox']['progress'];
      }
    }
  }

  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

function senate_redirect_batch_finished($success, $results, $operations) {
  $messenger = \Drupal::messenger();
  if ($success) {
    $messenger->addMessage(t('Number of nodes affected by batch: @count', ['@count' => count($results)]));
  }
  else {
    $error_operation = reset($operations);
    $messenger->addMessage(
      t('An error occurred while processing @operation with arguments : @args',
        [
          '@operation' => $error_operation[0],
          '@args' => print_r($error_operation[0], TRUE),
        ]
      )
    );
  }
}
