<div class="modal fade modal_meetingnotices" id="meetingnotices" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal__dialog modal__dialog_v-centered">
    <div class="modal__content">
      <span class="modal__close" data-dismiss="modal" aria-hidden="true">&times;</span>
      <div class="modal__body">

        <div class="form">
          <div class="pageIn__ico not-selectable">
            <img src="../dist/images/titleIco/title-ico-51.png"
                 srcset="../dist/images/titleIco/title-ico-51-2x.png 2x">
          </div>
          
          <h2>Sign up for Committee
            Meeting Notices</h2>

          <div class="form__desc">
            <p>Enter your name and email below, then select
              what meeting notices you’d like to be notified about.</p>
          </div>

          <div class="am-row">
            <div class="am-col-sm-6 form-item form-type-text">
              <input type="text" class="form-text" placeholder="First Name"/>
            </div>
            <div class="am-col-sm-6 form-item form-type-text">
              <input type="text" class="form-text" placeholder="Last Name"/>
            </div>
          </div>

          <div class="form-item form-type-text">
            <input type="text" class="form-text" placeholder="Email"/>
          </div>

          <div class="form-checkboxes">
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox " type="checkbox" name="checkbox-1" id="checkbox-1-1" checked="">
              <label for="checkbox-1-1" class="option">Receive notifications for all committees
              </label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-2">
              <label for="checkbox-1-2" class="option">Agriculture and Wildlife</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-3">
              <label for="checkbox-1-3" class="option">Business, Commerce and Tourism</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
            <div class="form-item form-type-checkbox">
              <input class="form-checkbox" type="checkbox" name="checkbox-1" id="checkbox-1-4">
              <label for="checkbox-1-4" class="option">Education</label>
            </div>
          </div>

          <div class="captcha"><input data-drupal-selector="edit-captcha-sid" type="hidden" name="captcha_sid" value="31269">
            <input data-drupal-selector="edit-captcha-token" type="hidden" name="captcha_token" value="f19d80619d3bc41f1b2e5a824b14f5a0">
            <div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-captcha-response form-item-captcha-response">
              <label for="edit-captcha-response" class="js-form-required form-required">Math question</label>
              <span class="field-prefix">1 + 2 =</span>
              <input autocomplete="off" data-drupal-selector="edit-captcha-response" aria-describedby="edit-captcha-response--description" type="text" id="edit-captcha-response" name="captcha_response" value="" size="4" maxlength="2" class="form-text required" required="required" aria-required="true">

              <div id="edit-captcha-response--description" class="description">
                Solve this simple math problem and enter the result. E.g. for 1+3, enter 4.
              </div>
            </div>
          </div>

          <div class="form-actions">
            <input type="submit" class="form-submit" value="submit">
            <div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div></div>
          </div>





        </div>


      </div>    
    </div>
  </div>
</div>