<div class="modal fade" id="simpleModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal__dialog modal__dialog_v-centered">
    <div class="modal__content">
      <div class="modal__header">
        <button type="button" class="modal__close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Modal title</h4>
      </div>
      <div class="modal__body">
        ...
      </div>
      <div class="modal__footer">
        <button type="button" data-dismiss="modal">Close</button>
        <button type="button">Save</button>
      </div>
    </div>
  </div>
</div>