<div class="bShare section__bShare bShare_cl_a">
  <div class="bShare__bSoc">
    <div class="bShare__title">
      Share
    </div>
    <div class="bSoc bSoc_min bSoc_min_share bSoc_cl_b">

      <div class="bSoc__items">
        <div class="bSoc__item">
          <a target="_blank" href="#" class="bSoc__ico ss-icon ss-social-circle ss-facebook"></a>
        </div>
        <div class="bSoc__item">
          <a target="_blank" href="#" class="bSoc__ico ss-icon ss-social-circle ss-instagram"></a>
        </div>
        <div class="bSoc__item">
          <a target="_blank" href="#" class="bSoc__ico ss-icon ss-social-circle ss-twitter"></a>
        </div>
        <div class="bSoc__item">
          <a target="_blank" href="#" class="bSoc__ico ss-icon ss-social-circle ss-mail"></a>
        </div>
      </div>

    </div>

  </div>

  <div class="bShare__print">
    <a href="javascript:window.print()">
      <i class="ss-icon ss-glyphish-outlined ss-print"></i>
      Printer Friendly
    </a>
  </div>
</div>