<div class="bSoc bSoc_min">

  <div class="bSoc__items">
    <div class="bSoc__item">
      <a target="_blank" href="#">
        <img src="../dist/images/soc/soc-facebook.png"
             srcset="../dist/images/soc/soc-facebook-2x.png 2x"
             alt="">
      </a>
    </div>
    <div class="bSoc__item">
      <a target="_blank" href="#">
        <img src="../dist/images/soc/soc-twitter.png"
             srcset="../dist/images/soc/soc-twitter-2x.png 2x"
             alt="">
      </a>
    </div>
    <div class="bSoc__item">
      <a target="_blank" href="#">
        <img src="../dist/images/soc/soc-mail.png"
             srcset="../dist/images/soc/soc-mail-2x.png 2x"
             alt="">
      </a>
    </div>
  </div>

</div>