<div class="sSen__item">
  <a class="sSen__sLink" href="#">
    <span class="sSen__sImgWrap">
      <span class="sSen__sImg" style="background-image: url('../dist/images/senImg/<?php print $element[0]; ?>')"></span>
      <span class="sSen__sMask sSen__sMask_<?php print $element[1]; ?>"><?php print $element[1]; ?></span>
      <span class="sSen__sDis">district <?php print $element[2]; ?></span>
    </span>
    <span class="sSen__sName">
      <?php print $element[3]; ?>
    </span>
  </a>
</div>