<footer class="sFooter">
  <div class="bContainer">
    <div class="sFooter__top">
      <div class="logo sFooter__logo">
        <a href="#">
          <img src="../dist/images/logo.png" alt="logo">
          Oklahoma Senate
        </a>
      </div>
      <div class="navLinks">
        <a href="" class="navLinks__link navLinks__link_live">
          Live Proceedings
        </a>
        <a href="" class="navLinks__link">
          Track a Bill
        </a>
      </div>
    </div>

    <div class="sFooter__bottom">
      <div class="sFooter__col">
        <div class="sFooter__address">
          Oklahoma Senate
          2300 N Lincoln Blvd.,
          Oklahoma City, OK 73105
        </div>

        <a href="mailto:email@oksenate.gov">email@oksenate.gov</a>

      </div>

      <div class="sFooter__col">

        <ul class="menu">
          <li><a href="#">Senators</a></li>
          <li><a href="#">Legislation & Bills</a></li>
          <li><a href="#">Education</a></li>
          <li><a href="#">Committees</a></li>
          <li><a href="#">Calendar</a></li>
          <li><a href="#">Press & Media</a></li>
          <li><a href="#">Contacts</a></li>
        </ul>

      </div>

      <div class="sFooter__col">
        <div class="sFooter__img">
          <img src="../dist/images/tmp/finder-ico-img-1.png" srcset="../dist/images/tmp/finder-ico-img-1-2x.png 2x"  alt="">
        </div>
        <div class="btn">find your senator here</div>
      </div>
    </div>

  </div>
</footer>