<footer class="sFooter">
  <div class="bContainer">
    <div class="sFooter__top">
      <div class="logo sFooter__logo">
        <a href="#">
          <img src="../dist/images/logo-b.png" alt="logo">
          Oklahoma Senate
        </a>
      </div>
      <div class="navLinks">
        <a href="" class="navLinks__link navLinks__link_live">
          Live Proceedings
        </a>
        <a href="" class="navLinks__link">
          Track a Bill
        </a>
      </div>

      <a href="#"
         class="btn"
         data-toggle="modal"
         data-target="#newsletter">newsletter sign up</a>
    </div>

    <div class="sFooter__bottom">
      <div class="sFooter__col">

        <div class="sFooter__address">
          Oklahoma Senate <br>
          2300 N Lincoln Blvd.,<br>
          Oklahoma City, OK 73105
        </div>

        <a href="mailto:email@oksenate.gov">email@oksenate.gov</a>

        <div class="sFooter__note">
          Please only send technical inquiries <br>
          to the above email address.
        </div>

      </div>

      <div class="sFooter__col">

        <div class="sFooter__nav">
          <ul class="menu">
            <li><a href="#">Senators</a></li>
            <li><a href="#">Legislation & Bills</a></li>
            <li><a href="#">Education</a></li>
            <li><a href="#">Committees</a></li>
            <li><a href="#">Calendar</a></li>
            <li><a href="#">Press & Media</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>
        </div>

      </div>

      <div class="sFooter__col">

        <div class="sFooter__info">
          <div class="sFooter__img">
            <img src="../dist/images/tmp/find-senator-img-1.png" srcset="../dist/images/tmp/find-senator-img-1-2x.png 2x"  alt="">
          </div>

          <h3>Find My Senator</h3>

          <div class="sFooter__btnWr">
            <a href="#" class="btn">find your senator here</a>
          </div>
        </div>

      </div>
    </div>

  </div>
</footer>

<?php include 'tpl/blocks/modals/newsletter.inc'; ?>
<?php include 'tpl/blocks/modals/meetingnotices.inc'; ?>
<!--only for slice!!!-->
<?php include 'tpl/includes/accessibilityCheck.inc'; ?>
<!--only for slice!!!-->