<footer class="sFooter">
  <div class="bContainer">
    <div class="sFooter__top">
      <div class="logo sFooter__logo">
        <a href="#">
          <img src="../dist/images/logo.png" alt="logo">
          Oklahoma Senate
        </a>
      </div>
      <div class="navLinks">
        <a href="" class="navLinks__link navLinks__link_live">
          Live Proceedings
        </a>
        <a href="" class="navLinks__link">
          Find My Senator
        </a>
        <a href="" class="navLinks__link">
          Track a Bill
        </a>
      </div>
    </div>

  </div>
</footer>