<header class="sHeader">

    <div class="sHeader__top">
      <div class="bContainer">
        <div class="logo sHeader__logo">
          <a href="#">
            <img src="../dist/images/logo.png" alt="logo">
            Oklahoma Senate
          </a>
        </div>
        <div class="navLinks">
          <a href="" class="navLinks__link navLinks__link_live">
            Live Proceedings
          </a>
          <a href="" class="navLinks__link">
            Find My Senator
          </a>
          <a href="" class="navLinks__link">
            Track a Bill
          </a>
        </div>
      </div>
    </div>

    <div class="sHeader__bottom">
      <div class="bContainer">

        <nav class="sHeader__nav">
          <a href="#" class="sHeader__btn-nav"></a>
          <div class="sHeader__menu-wrap">
            <ul class="menu">
              <li>
                <a href="#">Senators</a>
                <ul class="menu">
                  <li><a href="#">Lorem ips</a></li>
                  <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                  <li><a href="#">Lorem</a>

                    <ul class="menu">
                      <li><a href="#">Lorem ips</a></li>
                      <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                      <li><a href="#">Lorem ips</a>
                      </li>
                    </ul>

                  </li>
                </ul>
              </li>
              <li><a href="#">Legislation & Bills</a></li>
              <li class="menu-item--active-trail">
                <a href="#">Education</a>
                <ul class="menu">
                  <li><a href="#">Lorem ips</a></li>
                  <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                  <li><a href="#">Lorem</a>

                    <ul class="menu">
                      <li><a href="#">Lorem ips</a></li>
                      <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                      <li><a href="#">Lorem ips</a>
                      </li>
                    </ul>

                  </li>
                </ul>
              </li>
              <li><a href="#">Committees</a></li>
              <li><a href="#">Calendar</a></li>
              <li><a href="#">Press & Media</a></li>
              <li><a href="#">Contacts</a></li>
            </ul>
          </div>
        </nav>

        <div class="bSearch">
          <a href="#" class="bSearch__btn"></a>
        </div>

      </div>
    </div>
</header>