<header class="sHeader">

   <div class="bMessage">
     <a href="#" data-close-parent=".bMessage" class="bMessage__close"></a>
     <div class="bContainer">
        <p>In order to provide equal access and equal opportunity to people with diverse abilities, this site has been
          designed with full accessibility in mind. <a href="#">Click here to view.</a>
        </p>
      </div>
   </div>

    <div class="sHeader__top desktop-only">
      <div class="bContainer">
        <div class="logo sHeader__logo">
          <a href="#">
            <img src="../dist/images/logo.png" alt="logo">
            Oklahoma Senate
          </a>
        </div>
        <div class="navLinks">
          <a href="" class="navLinks__link navLinks__link_live">
            Live Proceedings
          </a>
          <a href="" class="navLinks__link">
            Find My Senator
          </a>
          <a href="" class="navLinks__link">
            Track a Bill
          </a>
        </div>
      </div>
    </div>

    <div class="sHeader__bottom">
      <div class="bContainer">
        <a href="#" class="sHeader__btn-mobile"></a>

        <div class="sHeader__navWrap">

          <nav class="sHeader__nav">
            <div class="sHeader__menu-wrap">
              <ul class="menu">
                <li>
                  <a href="#">Senators</a>
                  <ul class="menu">
                    <li><a href="#">Lorem ips</a></li>
                    <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                    <li><a href="#">Lorem</a>

                      <ul class="menu">
                        <li><a href="#">Lorem ips</a></li>
                        <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                        <li><a href="#">Lorem ips</a>
                        </li>
                      </ul>

                    </li>
                  </ul>
                </li>
                <li><a href="#">Legislation & Bills</a></li>
                <li class="menu-item--active-trail">
                  <a href="#">Education</a>
                  <ul class="menu">
                    <li><a href="#">Lorem ips</a></li>
                    <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                    <li><a href="#">Lorem</a>

                      <ul class="menu">
                        <li><a href="#">Lorem ips</a></li>
                        <li class="menu-item--active-trail"><a href="#">Lorem ips</a></li>
                        <li><a href="#">Lorem ips</a>
                        </li>
                      </ul>

                    </li>
                  </ul>
                </li>
                <li><a href="#">Committees</a></li>
                <li><a href="#">Calendar</a></li>
                <li><a href="#">Press & Media</a></li>
                <li><a href="#">Contacts</a></li>
              </ul>
            </div>
          </nav>

          <div class="navLinks mobile-only">
            <a href="" class="navLinks__link navLinks__link_live">
              Live Proceedings
            </a>
            <a href="" class="navLinks__link">
              Find My Senator
            </a>
            <a href="" class="navLinks__link">
              Track a Bill
            </a>
          </div>

        </div>

        <div class="bSearch">
          <a href="#" class="bSearch__btn"></a>
        </div>

      </div>
    </div>
</header>