<?php

/**
 * @file
 * Contains events_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_theme().
 */
function events_custom_theme() {
  return [
    'events_custom_upcoming' => [
      'render element' => 'children',
    ],
    'events_custom_home' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_preprocess_HOOK().
 */
function events_custom_preprocess_events_custom_upcoming(&$vars) {


  $vars['events'] = _events_custom_get_events();

  $vars['#attached']['library'][] = 'events_custom/events';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function events_custom_preprocess_events_custom_home(&$vars) {


  $vars['events'] = _events_custom_get_events();

//  dsm($vars['events']);

  $vars['#attached']['library'][] = 'events_custom/events';
}

function events_custom_preprocess_page(&$vars) {
  $vars['#attached']['library'][] = 'events_custom/events';

  $events = _events_custom_get_events();
  $events_sync_helper = \Drupal::hasService('events_custom.helper') ?
    \Drupal::service('events_custom.helper') : '';

  if (!empty($events_sync_helper) && !empty($events)) {
    $existing_nodes = $events_sync_helper->getNodesByType('committee_events');

    foreach ($events as $event) {
      $src_id = !empty($event->Id) ? $event->Id : '';
      $src_mod = !empty($event->LastModifiedTime) ? $event->LastModifiedTime : '';

      if (!empty($existing_nodes[$src_id]) && ($existing_nodes[$src_id]['src_modified'] != $src_mod)) {
        $events_sync_helper->updateNode($existing_nodes[$src_id]['nid'], $event);
      }
      elseif (empty($existing_nodes[$src_id])) {
        $nid = $events_sync_helper->createNode($event);
      }
    }
  }
}

function events_custom_test() {

//  dsm((string) \Drupal::httpClient()
//    ->get('https://sg001-harmony.sliq.net/00282/Harmony/en/api/Data/GetUpcomingEvents?lastModified=20200101223226000', ['timeout' => 0, 'headers' => [],])
//    ->getBody());

  $date = date("Ymd", strtotime('monday this week'));

  $response = (string) \Drupal::httpClient()
    ->get('https://sg001-harmony.sliq.net/00282/Harmony/en/api/Data/GetContentEntityByWeek/' . $date . '/-1', ['timeout' => 0, 'headers' => [],])
    ->getBody();


//  dsm(json_decode($response));
}

function _events_custom_get_events() {
  $date = date("Ymd", strtotime('monday this week'));
//  $date = '20191213';
  //$response = \Drupal::state()->get('events_custom.cache');
  if(empty($response)) {
    //dsm('not from cache');
    $response = (string) \Drupal::httpClient()
      ->get('https://sg001-harmony.sliq.net/00282/Harmony/en/api/Data/GetContentEntityByWeek/' . $date . '/-1', ['timeout' => 0, 'headers' => [],])
      ->getBody();

    //\Drupal::state()->set('events_custom.cache', $response);
  }

  $events =  json_decode($response);

  $rooms = [
    '/230/' => ['url' => '/room-230', 'title' => 'room 230'],
    '/419.*b/' => ['url' => '/room-419-b', 'title' => 'room 419-b'],
    '/419.*c/' => ['url' => '/room-419-c', 'title' => 'room 419-c'],
    '/419/' => ['url' => '/room-419', 'title' => 'room 419'],
    '/535/' => ['url' => '/room-535', 'title' => 'room 535'],
  ];

  if(!empty($events)) {
    foreach ($events as &$event) {
      //falback value
      $event->location_url = '/audio-video';
      $event->location_title = 'view';
      if(!empty($event->Location)) {
        $loc = strtolower($event->Location);
        foreach ($rooms as $pattern => $room_info) {
          if(preg_match($pattern, $loc)) {
            $event->location_url = $room_info['url'];
            $event->location_title = $room_info['title'];
            break;
          }
        }
      }
    }
  }

  return $events;
}

/**
 * Implements hook_cron().
 */
function events_custom_cron() {
  $cron_config = \Drupal::configFactory()->getEditable('events_custom.settings');
  $interval = $cron_config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;
  $request_time = \Drupal::time()->getRequestTime();

  $next_execution = \Drupal::state()->get('events_custom.next_execution', 0);

  if ($request_time >= $next_execution) {
    \Drupal::logger('events_custom')->notice('events_custom ran');
    if (\Drupal::state()->get('events_custom_show_status_message')) {
      \Drupal::messenger()->addMessage(t('events_custom executed at %time', ['%time' => date('c')]));
      \Drupal::state()->set('events_custom_show_status_message', FALSE);
    }

    \Drupal::state()->set('events_custom.next_execution', $request_time + $interval);
    \Drupal::state()->set('events_custom.prev_execution', $request_time);

    $queue = \Drupal::queue('events_custom');
    $events = _events_custom_get_events();
    $events = !empty($events) ? $events : [];
    $item = (object) ['events' => $events];

    $queue->createItem($item);
  }
}
